import fs from "node:fs";
import assert from "node:assert/strict";
import test from "node:test";
import { bilingualKeywordParityOverrides } from "../scripts/content-store.mjs";
const read=p=>JSON.parse(fs.readFileSync(p,"utf8"));
const issue=read("content/issues/v06-i04.json");
const slugs=issue.articles;
const refText=r=>typeof r==="string"?r:r?.text||"";
function urlPart(value){const start=value.search(/https?:\/\//iu);if(start<0)return null;const tail=value.slice(start);const markers=[/\s+\(?(?:adresinden|adresine)\b/iu,/\s+\(?(?:erişim tarihi|erişildi|erişim)\b/iu,/\s+\(?(?:accessed|retrieved)\b/iu];let end=tail.length;for(const marker of markers){const i=tail.search(marker);if(i>=0)end=Math.min(end,i);}return tail.slice(0,end);}
test("V6I4 is canonical locale-split metadata-v2 content",()=>{assert.equal(slugs.length,8);assert.equal(new Set(slugs).size,8);for(const slug of slugs){const base=`content/articles/${slug}`;const meta=read(`${base}/metadata.json`);assert.equal(meta.schemaVersion,2,slug);assert.equal(meta.journal.volume,6,slug);assert.equal(meta.journal.issue,4,slug);assert.equal(meta.dates.published,"2025-09-01",slug);assert.deepEqual(fs.readdirSync(`${base}/fulltext`).filter(x=>x.endsWith(".json")).sort(),["en.json","tr.json"],slug);for(const locale of ["en","tr"]){const ft=read(`${base}/fulltext/${locale}.json`);assert.deepEqual(meta.keywords?.[locale]||[],ft.keywords||[],`${slug}/${locale} keyword mismatch`);const ids=(ft.sections||[]).map(s=>s.id);assert.equal(ids.length,new Set(ids).size,`${slug}/${locale} duplicate section id`);for(const [i,r] of (ft.references||[]).entries()){const url=urlPart(refText(r));if(url)assert.doesNotMatch(url,/\s/u,`${slug}/${locale} ref ${i+1}: ${url}`);}}assert(!bilingualKeywordParityOverrides.has(slug),`${slug}: V6I4 must not depend on loader override`);}});
test("V6I4 source-verified keyword and structure decisions remain intact",()=>{const kolos="rusyanin-bolgesel-guvenlikteki-rolu-uzerine-bir-inceleme-kolektif-guvenlik-antlasmasi-orgutu-ve";const km=read(`content/articles/${kolos}/metadata.json`);assert.deepEqual(km.keywords.en,["Central Asian security","counterterrorism strategies","CSTO","Islamic radicalism","Russia’s foreign policy","transnational jihadist networks"]);assert.deepEqual(km.keywords.tr,["Orta Asya güvenliği","teröre karşı mücadele stratejileri","KGAÖ","İslami radikalizm","Rusya’nın dış politikası","ulusötesi cihatçı ağlar"]);const ken=read(`content/articles/${kolos}/fulltext/en.json`);const ktr=read(`content/articles/${kolos}/fulltext/tr.json`);assert.equal(ken.references.length,70);assert.equal(ktr.references.length,70);const wef="dunya-ekonomik-forumunun-kuresellesme-surecindeki-etkisinin-ekonomi-politik-elestirisi";const wm=read(`content/articles/${wef}/metadata.json`);assert.deepEqual(wm.keywords.tr,["ekonomik küreselleşme krizi","kapitalist rant arayışı","küresel sermaye birikimi","mekansal-zamansal düzeltme","neoliberalizm"]);assert.equal(read(`content/articles/${wef}/fulltext/en.json`).references.length,35);assert.equal(read(`content/articles/${wef}/fulltext/tr.json`).references.length,35);const young="genc-cin-ve-genc-cinliler-cinde-aydinlanma-yeni-kultur-hareketi-ve-yeni-siyasal-bicimlenme";const ym=read(`content/articles/${young}/metadata.json`);assert.deepEqual(ym.keywords.en,["China","4 May","New Culture Movement","New Youth","Communist Party of China"]);assert.deepEqual(ym.keywords.tr,["Çin","Çin Komünist Partisi","4 Mayıs","Yeni Gençlik","Yeni Kültür Hareketi"]);const yen=read(`content/articles/${young}/fulltext/en.json`);const ytr=read(`content/articles/${young}/fulltext/tr.json`);assert.equal(yen.sections.length,7);assert.equal(ytr.sections.length,8);assert.equal(yen.references.length,28);assert.equal(ytr.references.length,29);});
test("V6I4 catalog is localized and no longer legacy-current",()=>{const c=read("content/catalog.json");for(const slug of slugs){assert(c.fulltext.localized.includes(slug),slug);assert(!c.fulltext.current.includes(slug),slug);assert(!c.fulltext.en_archive.includes(slug),slug);}});
