export type EditorialCopy = {
  title: string;
  subtitle?: string;
  paragraphs: string[];
};

type LocalizedEditorial = {
  tr: EditorialCopy;
  en: EditorialCopy;
  issuePdfPage?: number;
};

export const archivedEditorials: Record<string, LocalizedEditorial> = {
  "5-1": {
    tr: {
      title: "Dolar hegemonyasının çöküşü adil uluslararası düzenin yolunu açıyor",
      paragraphs: [
        "İkinci Dünya Savaşı’ndan sonra, Bretton Woods sistemiyle temeli atılan ABD’nin dünyaya dayattığı dolar boyunduruğu düzeni adım adım çöküyor. Bu çöküş, nesnel bir durum. Söz konusu düzenin sahipleri de bu sistemin dünya ölçeğinde yıkıcı etkilerini tecrübe eden gelişmekte olan ülkeler de dolar hegemonyasının çökmekte olduğunu açık bir şekilde saptıyor. Peki uluslararası alanda dolarsızlaşma sürecinin nasıl etkileri olmaktadır, emperyalist merkezlerde ve gelişen dünya ülkelerinde bu gelişme karşısında izlenen politikalar hangi sonuçlara yol açacaktır? Elinizdeki sayımızda bu konuya odaklanıyoruz.",
        "Çok kutupluluğun gelişmesiyle dolarsızlaşma süreci arasında paralel bir ilişki olduğu görülmektedir. Dolar hegemonyasının yıkılmasının hem nedeni hem de sonucu olarak dünya çok kutuplulaşmaktadır. ABD önderliğindeki Atlantik cephesinin baş hedefine koyduğu Rusya ve Çin’in inşa ettiği alternatif finansal işbirliği çabaları giderek somutlaşmaktadır. Daha önemlisi, bu çabaların giderek bir gelişen dünya inisiyatifi haline gelmekte oluşudur.",
        "Dolar hegemonyasının çöküş süreci, yaklaşık 80 yıldır emperyalizmin finansal sistem aracılığıyla zapturapt altına aldığı dünyanın nefes almasını sağlamaktadır. Gelişmekte olan ülkeler arasında milli paralarla ticaret, merkez bankaları arasında ortak politikaların geliştirilmesi, ABD’nin finansal hegemonyasının en önemli araçlarından biri olan SWIFT’e alternatif ödeme sistemlerinin geliştirilmesi ve BRICS+6 bünyesinde bu doğrultuda yürütülen çalışmalar, dolar imparatorluğunun çözülmesi sürecini hızlandırmaktadır. Yine, dolar hegemonyasının aracısı görevi yerine getiren IMF ve Dünya Bankası’nın yerine Asya Altyapı Yatırım ve Kalkınma Bankası ve Yeni Kalkınma Bankası gelişen dünya için alternatif finansman kaynağı haline gelmektedir. Bunun yanı sıra, karşılıklı yararı esas alan fonlarla desteklenen Kuşak ve Yol Girişimi, çok taraflı uluslararası işbirliğinde çığır açan bir modeli temsil etmektedir. Böylece bir uluslararası haraç mekanizması işlevi gören Atlantik merkezli finansal sistemin yerine, gelişmekte olan devletlerin ihtiyaçlarına uygun olan bir finansal işbirliği mekanizması şekillenmektedir. Sonuç olarak, dolar hegemonyasının bitişi, daha adil bir uluslararası sistemin yolunu açmaktadır.",
        "***",
        "BRIQ Yönetim Kurulu Başkanı Adnan Akfırat ve Yayın Kurulu Koordinatörü Efe Can Gürcan, Eylül ayında Çin’de düzenlenen iki ayrı uluslararası Forum’un katılımcıları arasındaydı. 25-27 Eylül 2023’te Pingtan Adasında yapılan Dünya Politik Ekonomi Derneği’nin (WAPE) 16. Forumu’nda, Akfırat WAPE’nin Başkan Yardımcılığı’na, Gürcan da Konsey üyeliğine seçildi. Ayrıca Gürcan’a “2023 Politik Ekonomi Üstün Başarı Ödülü” verildi. “Çin’in Modernleşmesi ve Dünya Modernleşmesinin Görünümü” temasının ele alındığı Forum’da, Çin’in Batı’nın izlediği yoldan farklı yoldan giderek geliştirdiği modernleşme pratiği ile ulusal ve küresel ölçekte modernleşme için farklı yollar tartışıldı.",
        "Akfırat ve Gürcan, 28-29 Eylül 2023’te Xian kentinde, BRIQ’in Yayın Ortağı Kuzeybatı Politeknik Üniversitesi’nde (NPU) “4. Uluslararası Uygarlık ve Kültürel Kalkınma Akademik Forumu”na katılarak birer sunum yaptı. NPU’nun 85. yıldönümü dolayısıyla düzenlenen önemli bir akademik etkinlik olan bu Forumda ABD, Birleşik Krallık, Rusya, Yunanistan, Kanada, Meksika, Türkiye ve daha birçok ülkeden uzmanlar, akademisyenler ve öğrencilerin aralarında olduğu yaklaşık 200 kişinin katıldığı aktif tartışmalar oldu.",
        "Her iki etkinlikle ilgili ayrıntılı bilgiye, “Konferans Raporları” başlığı altında https://arastirma.istinye. edu.tr/merkezler/kuycam/yayinlar adresindeki BRIQ Online Working Papers serimizden ulaşabilirsiniz.",
      ],
    },
    en: {
      title: "The gradual collapse of dollar hegemony paves the way for a just international order",
      paragraphs: [
        "The dollar-centric global financial system, established by the US in the aftermath of World War II through the Bretton Woods Agreement, is steadily unraveling. This decline is an objective reality. Both the creators of this system and the developing countries, which have suffered its detrimental global effects, are becoming increasingly aware of the waning dominance of dollar hegemony. But what are the implications of the de-dollarization trend in the international sphere, and what will be the outcomes of the strategies adopted by both imperialist powerhouses and developing nations in response to this shift? This issue addresses these questions.",
        "There is a clear parallel between the rise of multipolarity and the de-dollarization process. The world is transitioning towards multipolarity, both as a driver and a result of the diminishing dollar dominance. The efforts of Russia and China to establish alternative forms of financial cooperation, despite facing opposition from the US-led Atlantic alliance, are gaining substantial ground. More significantly, these initiatives are becoming emblematic of a broader movement within the developing world.",
        "The weakening of dollar hegemony is offering the global community, long constrained by imperialist financial controls, a much-needed reprieve. This shift is marked by increased trade in national currencies among developing countries, the formulation of collaborative policies by central banks, the emergence of alternative payment systems to challenge the US-dominated SWIFT, and proactive measures within the BRICS+6 framework to hasten the dissolution of the dollar empire. Furthermore, institutions like the Asian Infrastructure Investment Bank and the New Development Bank are emerging as viable financial alternatives for the developing world, in contrast to the IMF and World Bank, which have traditionally perpetuated dollar hegemony. Additionally, the Belt and Road Initiative, underpinned by mutually beneficial funding, heralds a new era of multilateral international cooperation. Consequently, we are witnessing the formation of financial cooperation mechanisms that align with the vital needs of developing states, replacing the Atlantic-centric system that often functioned as a tool of international leverage and extortion. Ultimately, the decline of dollar hegemony is setting the stage for a more just international system.",
        "***",
        "BRIQ Chairman Adnan Akfırat and Editorial Board Coordinator Efe Can Gürcan participated in two distinct international forums held in China this September. During the 16th Forum of the World Association for Political Economy (WAPE), which took place on Pingtan Island from September 25-27, 2023, Akfırat was elected Vice President of WAPE, while Gürcan was elected as a WAPE Council member. Additionally, Gürcan received the WAPE’s “2023 Distinguished Achievement Award in Political Economy.” The forum’s theme, “China’s Modernization and the Outlook of World Modernization,” facilitated discussions on China’s unique modernization approach, distinct from Western models, and explored various pathways for national and global modernization.",
        "Akfırat and Gürcan also presented at the “4th International Academic Forum on Human Civilization and Cultural Development” held at the Northwest Polytechnic University (NPU), BRIQ’s publishing partner, in Xi’an on September 28–29, 2023. This significant academic event, commemorating the 85th anniversary of NPU, featured lively discussions with nearly 200 participants, including experts, academics, and students from the USA, UK, Russia, Greece, Canada, Mexico, Turkey, and several other countries.",
        "For detailed information about both events, visit BRIQ Online Working Papers at https://arastirma. istinye.edu.tr/merkezler/kuycam/yayinlar under the title “Conference Reports”.",
      ],
    },
  },
  "5-2": {
    tr: {
      title: "Afrika’da yükselen insanlık",
      paragraphs: [
        "Dünyanın, uluslararası sistem açısından yeni bir dönüm noktasında olduğu konusunda genel bir mutabakat bulunmaktadır. Hegemonyacılık mı kazanacak, yoksa gelişen dünyadaki milli devletlerin öncülüğünde daha adil bir uluslararası ilişkiler sistemi oluşturma davası mı? Bu bakımdan, Atlantik hegemonyacılığına karşı mücadele eden devletlerin, kendi aralarında kurdukları işbirliği platformlarını alternatif bir düzen için çekim merkezi haline getirebilmeleri belirleyici önem taşımaktadır. Yeni düzenin inşasında, somut başarılara ulaşılmasını sağlayacak yeterliliğe ve kapsayıcılığa sahip alternatif mekanizmaların kurulması gerekli görülmektedir.",
        "İlk çeyreğini tamamlamak üzere olduğumuz 21. yüzyıla Asya şimdiden damgasını vurmuştur. Artan nitelikli işgücü, yüksek teknolojide ulaştığı düzey, bilimsel atılımlarla genişleyen bilgi birikimi ve büyüyen ekonomisi ile başta Çin olmak üzere Asya’nın başarıları gıpta ile izlenmektedir.",
        "Asya bu yükselişinde yalnız değildir. Güney Amerika’nın yanı sıra, zengin doğal kaynakları, genç işgücü ve göreceli olarak istikrarlı büyüme yönelimiyle, Afrika da ayağa kalkmaktadır. Halihazırda, yeni uluslararası düzenin en önemli girişimlerinden biri olan BRICS’te Güney Afrika Cumhuriyeti (GAC), öncü bir rol oynamaktadır. Bunun yanı sıra, yüzyıllardır sömürülen Afrika ülkelerinde Batı işbirlikçisi iktidarlar son yıllarda teker teker yıkılmaktadır. 1960’larda bağımsızlıklarına kavuşan Afrika ülkelerinde, 2010’larda başlayan ikinci bağımsızlık rüzgârı hem kıtayı hem de sömürgecileri sarsmaktadır. Mali, Burkina Faso ve Nijer’deki iktidar değişiklikleriyle işbaşına gelen yönetimlerin, Batı tahakkümüne karşı geliştirdiği ortak irade Afrika’nın tamamında bağımsızlıkçı cereyanın güçlenmesini sağlamıştır.",
        "Kurulduğu dönemde Bağlantısızlar Hareketi’nin başını çeken Afrika devletleri Asya’yla işbirliğine yönelirken, Asya’da Atlantikçi kuvvetlerle boğuşan devletler de Afrika ile yakınlaşmaktadır. Çin, Rusya, Türkiye, İran ve Hindistan’ın Afrika ile çeşitli alanlardaki ortaklıkları hızla gelişmektedir. Bunun yanında, Batı karşısında giderek daha özerk politikalar izlemeye başlayan Suudi Arabistan gibi devletlerle genişleyen işbirliği, Afrika devletlerinin yeni sömürgecilikten kurtulma savaşında önemli katkılar yapmaktadır. Tek kutupluluğu sona erdiren bölgesel işbirlikleri rüzgârı Afrika’yı da kucaklamaktadır.",
        "Bu gelişmeler, kıta ölçeğinde olduğu kadar dünya genelinde de dengeleri değiştiren sonuçlara yol açmaktadır. Batı tahakkümünün kırılması, Afrika’daki zenginliklerin Afrika halklarının yararına kullanılması için imkân sağlamakta, aynı zamanda emperyalist müdahaleler nedeniyle engellenen güney-güney işbirliğini kolaylaştırmakta, böylece bütün tarafların yararına olumlu sonuçlar yaratmaktadır. Bu açıdan bakıldığında, Afrika’nın yeni sömürgeciliği alt etmesi, sadece Afrika’daki devletlerin değil, aynı zamanda gelişen dünya ülkelerinin tamamı açısından bir ortak amaç haline gelmektedir. Gelişen dünyadaki devletlerin, neoliberalizme ve küreselleşmeciliğe karşı kurtuluş savaşı Afrika’da yükselmektedir.",
        "21. Yüzyıl’ın sadece Asya değil Afrika yüzyılı olacağı görülmektedir.",
        "***",
        "Bu sayı ile dört buçuk yaşına giren BRIQ, yeni bir atılım başlatıyor. Dergimiz ilk sayısından itibaren Türkiye’de Türkçe ve İngilizce olarak basılıyordu. Bu sayıdan itibaren dergimizin matbaada baskısı sadece Türkçe olacak. İngilizcesini ise e-dergi olarak yayımlayacağız. Web sitemizde BRIQ’in Türkçesini ve İngilizcesini e-dergi olarak bulabilirsiniz. BRIQ’i Çince, Arapça, Farsça, Rusça, İspanyolca, Fransızca dillerinde de e-dergi olarak yayınlamak için çalışmalar başladı. BRIQ’i Kuşak ve Yol Girişimi’nde yer alan ülkelerin başlıca dillerinde yayımlanan bir dergi haline getirmek için yola çıkmış bulunuyoruz. Okurlarımızın katkısı ile bu büyük görevi yerine getirmeyi umut ediyoruz.",
      ],
    },
    en: {
      title: "The rise of humanity in Africa",
      paragraphs: [
        "There is a broad consensus that we are at a pivotal moment of change in the international system. The debate centers on whether hegemony will continue to dominate or a more equitable system of international relations will emerge, led by nation-states in the developing world. Critically, the ability of states challenging Atlantic dominance to transform their collaborative platforms into a hub for an alternative order is vital. Creating this new order demands the development of alternative mechanisms endowed with the capability and inclusiveness necessary for tangible achievements.",
        "Asia has decisively marked its influence on the 21st century, as we draw close to the end of its first quarter. The continent’s progress, with China leading the way, is lauded for its burgeoning skilled labor force, advanced technological achievements, expanding knowledge through scientific innovations, and economic growth.",
        "Asia’s ascent is not happening in isolation. Along with Latin America, Africa is also on the rise, buoyed by its abundant natural resources, youthful labor force, and relatively steady growth trend. Presently, the Republic of South Africa is playing a pivotal role in the BRICS, a key initiative shaping the new world order. Furthermore, governments in Africa that once collaborated with the West and were exploited for centuries are now being systematically dismantled. The second wave of independence movements, starting in the 2010s and following the initial wave of independence in the 1960s, is significantly impacting both the continent and its former colonizers. The new governments emerging from changes in leadership in countries like Mali, Burkina Faso, and Niger are fortifying the pan-African movement for independence, united in their opposition to Western hegemony.",
        "African nations, which had led the Non-Aligned Movement at its inception, are increasingly collaborating with Asia. Similarly, Asian countries facing challenges from Atlanticist influences are seeking stronger ties with Africa. Partnerships across a wide range of sectors with nations such as China, Russia, Türkiye, Iran, and India are flourishing at an unprecedented pace. Moreover, deepening cooperation with countries like Saudi Arabia, which are pursuing more independent policies from the West, is significantly aiding African nations in their effort to break free from neocolonialism. The trend towards regional cooperation, which has contributed to the decline of the unipolar world order, is now encompassing Africa as well.",
        "These developments are shifting the balance of power not just on a continental level but globally as well. The erosion of Western hegemony is unlocking opportunities for Africa’s wealth to be utilized for the benefit of its people, enabling South-South cooperation previously impeded by imperialist actions, and consequently generating positive results for all stakeholders. Through this lens, overcoming neocolonialism in Africa is emerging as a shared objective, not just for African nations but for the entire developing world. The movement to break free from the constraints of neoliberalism and globalization is gaining momentum across Africa.",
        "It is becoming clear that the 21st century will be defined not only by Asia’s ascendance but also by Africa’s resurgence.",
        "***",
        "With this issue, BRIQ marks four and a half years of publication and embarks on a new venture. Since our debut, the journal has been available in both Turkish and English. However, from this issue forward, the print edition will be exclusively in Turkish, while the English version will transition to an electronic format. Both the Turkish and English e-journal versions of BRIQ are accessible on our website. We have also started efforts to release BRIQ in e-journal format in Chinese, Arabic, Persian, Russian, Spanish, and French. Our goal is to evolve BRIQ into a journal available in the main languages of the countries participating in the Belt and Road Initiative. With the support of our readers, we are hopeful of achieving this ambitious objective.",
      ],
    },
  },
  "5-3": {
    tr: {
      title: "Medeniyetlerin kaynaşma yolu: Kuşak-Yol ve İslam Dünyası",
      paragraphs: [
        "Son 10 yılda dünya çok hızlı bir bir değişim ve dönüşüm yaşıyor. Dönüşümün yönü, bu kez insanlığın yararına. ABD önderliğindeki Atlantik emperyalizmi, 30 yıl önce neo liberal küreselleşmecilik vasıtasıyla milli devletleri dümdüz edeceğini ilan etmişti. İçinden geçtiğimiz dönemde hegemonyacılık gerilerken milli devletlerin inisiyatifi ele aldığı görülüyor.",
        "Neoliberal küreselleşmeci ideolojinin tezi, “tarihin sonu”na gelindiği, sınırların ortadan kalktığı, dünyanın küresel bir köye dönüştüğü iddiasıydı. Dünya köyünün egemeni de Atlantik emperyalistleri olacaktı. Ama bu tezin öyle kolay kabul edilmeyeceğini bilen hegemonyacılık, “küresel köy”e karşı çıkanları bastırmak için başka bir tezi daha ortaya attı: Medeniyetler Çatışması! Buna göre, “tarihin sonu”nda insanlığın “altın çağı”na ulaşılmasını sağlayan “Batı medeniyeti”ne karşı, başta İslam olmak üzere “doğu medeniyetleri”nden kaynaklanan gerici (!) bir direniş olacaktı. Bu kavramsallaştırma son 30 yılda, Afrika’dan, Batı Asya’ya ve Uzak Asya’ya kadar dünyanın her yerindeki, özellikle de “insan haklarını ihlal” bahanesiyle yapılan emperyalist müdahalelerin ideolojik kılıfını oluşturdu. Atlantik emperyalizmi bugün de dünyadaki saflaşmayı şu şekilde sunmaktadır: “Özgür Batı medeniyeti”nin karşısında Afrika, Asya ve Latin Amerika milletlerinin “otoriter, milliyetçi” doğu medeniyeti. Bugün Filistin’de devam eden İsrail katliamları konusunda “Batı medeniyeti”nin yaklaşımı, bunun en tipik örneğidir. İslamofobinin, ırkçılığın ve her türden ayrımcılığın kaynağı burasıdır.",
        "Öte yandan, hegemonyacılığa karşı mücadele eden gelişen dünya devletlerinin programı ise medeniyetler arasında çatışmayı değil uyumu ve kaynaşmayı esas almaktadır. Bugün, İran’ın Rusya, Çin ve Latin Amerika ile, Rusya ve Çin'in Arap dünyası, Afrika ve İslam ülkeleri ile, Türkiye’nin Rusya, Çin ve Latin Amerika ile artan işbirliğinin güdüleyicisi hiç kuşkusuz hegemonyacılığa karşı ortaklık arayışı. Ama bu işbirliği, basit bir karşılıklı kazanç elde etme hedefinin ötesinde giderek daha fazla ortak değerler üzerinde şekillenmektedir. Gelişen dünya devletlerinin işbirliğinde kaynaşma vardır, paylaşma ve birbirlerine saygı vardır. Gelişen dünya, bağımsızlık, kamuculuk ve insancıllıkta buluşmaktadır.",
        "Farklı medeniyetler arasında günümüzdeki en somut işbirliğine, İslam ülkeleri ile Çin arasındaki ilişkilerin son 40 yılda aşama aşama gelişmesi örnek gösterilebilir. Bu gelişme üstelik, “bünyesindeki Müslümanlara soykırım yaptığı” suçlamasıyla Çin’i “İslam düşmanı” olarak göstermek için, ABD’nin dünya çapında kampanyalar yürüttüğü sırada gerçekleşti. Özellikle Kuşak ve Yol Girişimi’nin (KYG) ortaya atıldığı 2013 yılından sonra ivme kazanan bu ilişkilerin önemi, devasa ekonomik yatırımlarla sınırlı değildir. 2022 yılı resmi verilerine göre İslam ülkelerine KYG kapsamında yapılan yatırımların toplam miktarı 400 milyar doların üzerindedir. Ama bundan daha önemlisi, ortak kalkınmayı temel alan KYG’nin dünya siyasetinde dengeleri değiştirmesidir. Atlantik sisteminin oluşturduğu statüko sonucunda, kendi sınırları içinde mezhepler, etnik topluluklar arasında boğuşmalara ve kendi aralarında silahlı çatışmalara mahkum edilmek istenen İslam ülkeleri bu cendereyi kırmaktadır.",
        "Tarihi İpek Yolu, farklı kültürler arasında işbirliği, karşılıklı öğrenme ve hoşgörüyü geliştirmiş ve dünya uygarlığının ilerlemesini sağlamıştı. 21. Yüzyılın İpek Yolu Kuşak ve Yol Girişimi, medeniyetlerin buluşması, kaynaşması ve giderek yeni bir medeniyete ulaşılmasının yolunu açmaktadır.",
      ],
    },
    en: {
      title: "Belt&Road and Islamic World: The Pathway of Civilizations Converging",
      paragraphs: [
        "Over the past decade, the world has witnessed rapid changes and transformations, largely to humanity’s benefit. Thirty years ago, Atlantic imperialism, led by the United States, proclaimed through neoliberal globalization that it would flatten nation-states. In the current era, as hegemonism wanes, nation-states are increasingly asserting themselves. The thesis of neoliberal globalization claimed that we had reached the “end of history,” where borders would disappear, and the world would become a global village dominated by Atlantic imperialists. However, anticipating resistance to this view, hegemonism introduced the “Clash of Civilizations” thesis to suppress opposition to the “global village.” This theory posited a reactionary resistance from “Eastern civilizations,” primarily Islam, against the “Western civilization” poised to usher humanity into its “golden age.” This framework has ideologically supported imperialist interventions globally, especially those justified by “human rights violations,” for the last three decades. Today, Atlantic imperialism frames global alignments as “Free Western civilization” versus the “authoritarian, nationalist” Eastern civilizations of Africa, Asia, and Latin America. The ongoing violence in Palestine by Israel exemplifies the stance of “Western civilization.” The source of Islamophobia, racism, and all forms of discrimination lies here.",
        "Conversely, the agenda of developing states combating hegemonism focuses on fostering harmony and integration among civilizations, not conflict. The driving force behind increasing cooperation between Iran, Russia, China, and Latin America; between Russia and China and the Arab world, Africa, and Islamic countries; and between Turkey, Russia, China, and Latin America is undoubtedly a collective stance against hegemonism. This cooperation increasingly rests on shared values beyond mere mutual gain. Among these developing states, there is a spirit of integration, sharing, and mutual respect. The developing world is uniting around independence, public welfare, and humanitarian values.",
        "A prime example of inter-civilizational cooperation today is the evolving relationship between Islamic countries and China over the last 40 years. This relationship has strengthened even as the US has led global campaigns accusing China of committing “genocide against its Muslim population,” attempting to paint China as an “enemy of Islam.” Since the launch of the Belt and Road Initiative (BRI) in 2013, the significance of these relationships has grown, encompassing massive economic investments. According to 2022 official data, investments in Islamic countries under the BRI exceed $400 billion. More crucially, the BRI, founded on joint development, is shifting the balance of world politics. Islamic countries, previously constrained by the Atlantic system’s status quo into internal sectarian and ethnic conflicts, are breaking free from this bind.",
        "The historic Silk Road facilitated cooperation, mutual learning, and tolerance among diverse cultures, propelling the advancement of world civilization. The 21st-century Silk Road, embodied by the Belt and Road Initiative, is forging pathways for the convergence and eventual creation of a new civilization.",
      ],
    },
    issuePdfPage: 5,
  },
  "5-4": {
    tr: {
      title: "Çok kutuplu dünyada Kuşak-Yol ve Türk Devletleri Teşkilatı",
      paragraphs: [
        "Çok kutuplu dünyanın ayırt edici özelliklerinden birinin, giderek güçlenen ve bölgesel düzeyden küresel ölçeğe doğru etki alanını genişleten bölgesel işbirliği platformları olduğu söylenebilir. Kuşkusuz ekonomik, siyasi ya da askeri ilişkiler temelinde ülkelerin bir araya geldiği bölgesel oluşumlar çok kutuplulaşma öncesinde de vardı. Fakat bu dönemde, Atlantik hegemonyacılığının, doğrudan dahil olarak ya da vekil olarak kullandığı devletler aracılığıyla bu örgütleri yönlendirebildiği bilinmektedir. Günümüzde Atlantik’in özellikle ekonomide ve yüksek teknolojide üstünlüğünü kaybetmesi, hegemonyacılığın da gerilemesine neden olan bir ortam yarattı. Çok kutupluluk ile şekillenen bu zemin, gelişen dünya devletlerinin artık kendi çıkarlarını gerçekleştirmelerini sağlayacak bölgesel işbirliği platformlarının yolunu açtı. Küresel ölçekte BRICS, Asya’yı kapsamakla kalmayıp Belarus üzerinden Avrupa’ya da uzanan Şanghay İşbirliği Örgütü (ŞİÖ), Latin Amerika’da Amerika Halkları için Bolivarcı İttifak (ALBA) ve Güney Amerika Ulusları Birliği (UNASUR) ve son olarak Afrika’da Sahel Devletleri İttifakı ivme kazanmıştır. Bu gelişmelere koşut olarak, daha önceki dönemden kalan bölgesel platformlar da hegemonyacılığın tahakkümünden kurtuldukça bölge ülkelerinin kendi çıkarlarına odaklanabilmesine olanak sağlamaktadır. 2019 yılında Türk Devletleri Teşkilatı’nın (TDT) kurulması da çok kutuplu dünya zemininde ortaya çıkan bir gelişmedir.",
        "Nesnel olarak bugün küresel düzeyde ortaya çıkan cepheleşmede, ABD önderliğindeki Atlantik cephesi ile başta Asya’nınkiler olmak üzere, Afrika ve Latin Amerika’nın milli devletleri karşı karşıya bulunmaktadır. Bu küresel cepheleşmede Atlantik’in en önemli hedefi dünyadaki hegemonyacılığın güç kaybetmesinde belirleyici olan Asya’nın yükselişini durdurmaktır. Bu çabada iki önemli yoğunlaşma alanı, Batı Asya ve Orta Asya olarak görünmektedir.",
        "Öte yandan, Çin’in önerdiği, gelişen dünya ülkelerinin ortak kalkınmasını, paylaşarak gelişmesini ve ortak refahını hedefleyen çok taraflı işbirliği platformu Kuşak ve Yol Girişimi (KYG) açısından her iki bölge de stratejik bir konumda bulunmaktadır. 11’inci yılını doldurmak üzere olan KYG kapsamında ulaştırma ve enerji koridorları Türk Devletleri Teşkilatı üyesi ülkelerin üzerinde olacaktır. Türk Devletleri Teşkilatı’nın ve üyelerinin KYG içinde üstleneceği etkin rol, uluslararası alanda önemli değişikliklere yol açma potansiyeline sahiptir.",
        "Türkiye, Orta Asya’daki Türk cumhuriyetleriyle hem Diyalog Ortağı olarak bulunduğu ŞİÖ’de hem de Türk Devletleri Teşkilatı’nda birliktedir. Bu cumhuriyetler aynı zamanda ŞİÖ’de Rusya, Çin, İran ve Hindistan ile ortaklık içindedir. Ayrıca Rusya ile Kolektif Güvenlik Anlaşması Örgütü’nde ve Avrasya Ekonomik Birliği’nde, Çin ile de KYG kapsamında işbirliği halindedir.",
        "Atlantik’in hedefinde yer alan ama yanında tutmaya çalıştığı Türkiye’nin, sadece ekonomide değil uluslararası siyasette de Rusya, Çin ve İran ile günümüzde daha fazla netleşen kader birliği, Türk Devletleri Teşkilatı’nı Asya’da bir köprü haline getirebilir. TDT’nin bölge ülkeleriyle ortaklaşan politikalar izleyerek güçlenmesi, Atlantik hegemonyacılığını zayıflatır. Bu durum, sadece Türkiye’nin değil Rusya’nın, Çin’in, İran’ın da elini güçlendirir. Bu, TDT'nin kaderleri ortak olan Asya ülkelerinin beraber sahipleneceği bir örgüt haline getirilmesiyle sağlanacaktır.",
      ],
    },
    en: {
      title: "The BRI and the Organization of Turkic States in a Multipolar World",
      paragraphs: [
        "One might argue that a defining characteristic of the multipolar world is the rise of regional cooperation platforms that are increasingly gaining strength and extending their influence from the regional to the global level. Certainly, regional organizations where countries convened based on economic, political, or military ties existed even prior to the onset of multipolarity. However, it is widely recognized that during this period, Atlantic hegemonism was capable of steering these organizations, either through direct involvement or via proxy states. In contrast, the current decline in Atlantic supremacy, particularly in the realms of economics and high technology, has fostered an environment that has contributed to the retreat of hegemonism. This new multipolar context has paved the way for regional cooperation platforms that enable developing nations to more effectively pursue their own interests. On a global scale, organizations such as BRICS, the Shanghai Cooperation Organization (SCO)—which extends not only across Asia but also reaches Europe via Belarus—alongside the Bolivarian Alliance for the Peoples of Our America (ALBA) and the Union of South American Nations (UNASUR) in Latin America, and more recently the Sahel States Alliance in Africa, have gained significant momentum. Concurrently, earlier regional platforms, as they increasingly extricate themselves from hegemonic dominance, have provided nations within these regions with the opportunity to focus on their own interests. The establishment of the Organization of Turkic States (OTS) in 2019 is a further development that has emerged within the framework of a multipolar world.",
        "At the present time, the nation-states of Asia, Africa, and Latin America find themselves objectively positioned in opposition to the US-led Atlantic front, within the broader context of the global confrontation that has emerged. In this global struggle, the Atlantic bloc’s most significant objective is to halt the rise of Asia, a rise that plays a pivotal role in undermining global hegemony. In this endeavor, two critical focal areas have emerged: West Asia and Central Asia. Conversely, both regions hold strategic importance for the Belt and Road Initiative (BRI), a multilateral cooperation platform proposed by China that seeks to foster shared development and prosperity among developing nations.",
        "As the BRI approaches its 11th anniversary, it is evident that the transportation and energy corridors under this initiative will traverse the member states of the OTS in this region. The effective participation of the OTS and its members within the BRI holds the potential to precipitate significant shifts on the international stage.",
        "Türkiye, alongside the Turkic republics of Central Asia, aligns itself within both the SCO, where it holds Dialogue Partner status, and the OTS. These republics also maintain partnerships with Russia, China, Iran, and India within the SCO, cooperate with Russia through the Collective Security Treaty Organization and the Eurasian Economic Union, and collaborate with China within the framework of the BRI.",
        "Türkiye, which is both a target of the Atlantic bloc and a state it seeks to retain as an ally, finds its fate increasingly intertwined with that of Russia, China, and Iran—not only in economic matters but also in international politics. This alignment has the potential to transform the OTS into a bridge within Asia. Strengthening the OTS through policies that are aligned with the interests of regional states would further weaken Atlantic hegemonism. Consequently, this would not only bolster Türkiye’s position but also enhance the strategic standing of Russia, China, and Iran. This potential will be realized by making the OTS an organization that is embraced by all the nations of Asia that share a common destiny.",
      ],
    },
    issuePdfPage: 5,
  },
  "6-1": {
    tr: {
      title: "Asya’dan yükselen yeni uygarlığın önündeki görev",
      paragraphs: [
        "Günümüzde gelişen dünya ülkelerinin önündeki en önemli görevin, sürdürülebilir kalkınmayı gerçekleştirmek olduğu biliniyor. Bu amaç doğrultusunda ülkelerin, bilim ve teknoloji alanında yüksek nitelikli bir atılımı gerçekleştirmesi gereklidir. Ancak bunun için kestirme bir yol olmadığı bilinmektedir. Ülkenin kendi kalkınma yolunu çizmesi için, her bir ülke, halihazırdaki ve potansiyel olarak sahip olduğu kendi ulusal imkan ve kabiliyetlerini değerlendirecektir. Öncelikle mevcut ulusal kapasitenin değerlendirilmesini sınırlayan/engelleyen etkenler ortadan kaldırılmalıdır. İkinci olarak, kalkınma hedefine ulaşmak için, devlet ve toplumun potansiyeli harekete geçirilmelidir. Bunlar, kurumsal yapının bu amaca uygun olarak örgütlenmesiyle sağlanabilir.",
        "Sürdürülebilir kalkınmayı gerçekleştirmek için dayanılacak birincil kuvvet, en büyük üretici güç olan insandır. Başka bir deyişle, bir ülkenin sahip olduğu en önemli sermaye beşeri sermayedir. Gelişmekte olan ülkelerin kalkınmayı başarmak için, insanı merkeze alan uzun vadeli bir planlama stratejisini uygulamak dışında bir seçeneği yoktur. Bu stratejinin olmazsa olmazı, orta ve uzun vadeli olarak hedefleri belirlemek, devleti ve toplumu buna göre yeniden örgütlemektir. Mevcut neoliberal sistem içinde, güçlü olan yükselmekte, geride kalan kenarlara sürülmektedir. Oysa kalkınmanın gerçekten sürdürülebilir olması ve başarıya ulaşması için, halkın topyekün seferber edilmesi gereklidir. Kalkınma planının toplumdaki eşitsizlikleri giderecek şekilde halkçı ve toplumcu bir temelde inşa edilmesi ile halkın tamamı seferber edilebilir.",
        "Gelişmiş ülkelerin öncülüğündeki emperyalist sistemin, gelişmekte olan ülkelere dayattığı neoliberal serbest piyasa reçetelerinin kalkınma açısından herhangi bir getirisinin olmadığı açıkça görülmektedir. Dahası söz konusu dayatmalar, bu ülkelerin kendi özgün kalkınma hedefine ulaşmasını önlemekte ve emperyalist sisteme daha fazla bağımlılığına yol açmaktadır. Bu nedenle gelişmekte olan ülkelerin, kamusal çıkarı esas alan uzun vadeli bir stratejiyi oluşturması gerekliliği bulunmaktadır.",
        "Gelişen dünyanın, bilim ve teknoloji alanında kapatması gereken açığın büyüklüğü, başka bir zorunluluğu da önüne koymaktadır. Bugünkü dünya tablosunda emperyalist sistemin esaretinden kurtulmak için, güvenlikte olduğu gibi bilim ve teknoloji alanında da Küresel Güney ülkelerinin kendi aralarında güçbirliği yapmasına ihtiyaç vardır. Ülkelerin, daha üstün olduğu imkanlarını ve kabiliyetlerini diğerleriyle paylaşacağı ve zorluklara karşı dayanışma içinde olacağı, böylece her ülkenin kendi ihtiyaçlarının karşılanabileceği bir ortaklık hayata geçirilir.",
        "Küresel Güney’de bilim ve teknoloji alanında işbirliğinin kurulması için, Kuşak ve Yol Girişimi (KYG) yola çıkmış bulunuyor. KYG kapsamında, öğrenci ve bilim insanları değişiminden ortaklaşa düzenlenen bilimsel etkinliklere ve çeşitli ülkelerin birlikte inşa ettiği araştırma laboratuvarlarından yüksek nitelikli bilimsel ve teknolojik ortak projelere kadar bir dizi işbirliği hayata geçiriliyor. Ancak halen yolun başındayız. Gelişen dünya ülkelerinin, diğer alanlardaki güçbirliğinin yanı sıra bilimsel ve teknolojik alanda da işbirliği kurması, insanlığın eşitlikçi ve adil bir dünyayı inşa etmesi yolunda önemli bir adım olacaktır.",
      ],
    },
    en: {
      title: "The task facing the emerging civilization from Asia",
      paragraphs: [
        "The primary challenge confronting developing nations globally is the attainment of sustainable development. To achieve this objective, governments must undertake substantial strides in the realm of research and technology. Nonetheless, it is acknowledged that there are no shortcuts for this. To establish its own growth trajectory, each nation will assess its existing and potentially accessible national resources and capabilities. Initially, impediments that restrict or obstruct the evaluation of the existing national capacity must be eradicated. Secondly, to attain the developmental objective, the potential of the state and society must be activated. These objectives can be attained by structuring the state’s institutional framework in alignment with this aim.",
        "The principal force for attaining sustainable development is humans, the fundamental productive force. That is, human capital is a country’s most important resource. Developing nations must implement a sustainable, human-centered planning strategy to attain development. The essential element of this strategy is to establish medium- and long-term objectives and to restructure the state and society accordingly. The prevailing neoliberal system prioritizes the powerful and sidelines the marginalized. However, engaging the entire populace is essential for genuinely sustainable and effective development. To mobilize the entire people, the development plan must be founded on principles that address societal disparities and respect the interests of the whole public.",
        "It is clear that the imperialist system’s imposition of neoliberal free market principles on developing nations yields no benefits in terms of development. Furthermore, these impositions hinder these nations from realizing their distinct developmental objectives and result in further reliance on the imperialist system. Consequently, emerging nations must formulate a long-term plan grounded in the public interest.",
        "Another imperative is the significant scientific and technological gap that the emerging world must bridge with industrialized nations. In the contemporary era, to liberate themselves from the constraints of the imperialist system, nations of the Global South must establish an alliance in the domains of science and technology, akin to their collaboration in the security field. In order to address each nation’s needs, a partnership is formed in which nations pool their superior resources and talents and support one another in the face of adversity.",
        "The Belt and Road Initiative (BRI) has initiated collaboration in science and technology inside the Global South, among other fields. Countries involved in the BRI are engaging in various collaborations in scientific cooperation, including exchanges of students and scientists, co-organized scientific events, jointly constructed research laboratories, and high-quality collaborative scientific and technological projects. Nevertheless, we remain at the inception of the journey. Together with their collaboration in other areas, emerging nations’ collaboration in the scientific and technological spheres will be a major step toward creating a fair and just world for all people.",
      ],
    },
  },
  "6-2": {
    tr: {
      title: "Asya’daki Devrim Mayası",
      paragraphs: [
        "Son 25 yılda dünyanın jeopolitik çehresinde çok önemli değişiklikler oldu ve olmaya devam ediyor. ABD merkezli sistem salt ekonomik olarak değil, aynı zamanda siyasal, ideolojik ve kültürel düzlemde de gerilemeye başladı. Buna koşut olarak, Çin başta olmak üzere Asya, dünyanın üretim motoru haline geldi. Bunun yanı sıra, gelişen dünyanın öncü ülkeleri de ekonomik olarak yükselişe geçti.",
        "Bu değişikliklerin en önemli sonucu, İkinci Dünya Savaşı’ndan sonra kurulan ve merkezinde Avrupa-ABD ittifakının bulunduğu Atlantik hegemonyacılığının, artık süreçleri belirleme gücünün kalmadığının ortaya çıkması oldu. Atlantik’in dünya hegemonyasını dayatmak üzere inşa edilen “kurallara dayalı düzen” çöküyor. 1991’de Sovyetler Birliği’nin yıkılmasından sonra ABD önderliğindeki tek kutuplu dünya düzeni de artık yok! ABD’nin de, Avrupa’nın da, gelişen dünya devletlerinin de siyasetlerini, günümüzde çok kutupluluk belirliyor.",
        "Dünya düzenine yön veren geleneksel kurumlar etkisini yitirirken, herkesin karşılıklı olarak kazandığı yeni tür uluslararası işbirlikleri güçleniyor. Kuşak ve Yol Girişimi ve Şanghay İşbirliği Örgütü ile giderek büyüyen BRICS+ gibi platformlarda bir araya gelen gelişen dünyanın devletleri, dünya düzeninde dönüşümü fiilen hayata geçiriyor. Bu yeni işbirlikleriyle, küreselleşmeci neo- liberal düzenden farklı ve ona alternatif olan, “egemenlik ve toprak bütünlüğüne karşılıklı saygı, saldırmazlık, iç işlerine karışmama, eşitlik ve karşılıklı yarar ve barış içinde bir arada yaşama” ilkeleri temelinde bir düzen, giderek etki alanını genişletiyor.",
        "21’inci yüzyılın ilk çeyreğini tamamlarken, dünya yüz yıl öncekine benzer ölçekte büyük bir dönüşüm yaşıyor. 20’nci yüzyılın ilk yıllarında, Asya’nın büyük medeniyetlerinin küllerinden doğmasını sağlayan büyük devrimler dünyayı sarsmıştı. Günümüzde, yine Asya önde ama bu kez yalnız değil. Asya’nın yanı sıra Afrika’nın, Latin Amerika’nın, gelişen dünyanın milletleri emperyalist tahakküme karşı kendi milli devletlerini ayağa kaldırıyor.",
        "20’nci yüzyılın başında Türkiye, Rusya, Çin ve İran dışında dünyanın tamamı sömürge durumundaydı. Asya’da ardı ardına gerçekleşen Rusya, Türkiye, İran ve Çin devrimleri, dünyanın dört bir tarafında emperyalizme karşı milli bağımsızlık hareketlerine ilham kaynağı olmuştu. 20’nci yüzyılın ortasından itibaren sosyalist önderlikli halk devrimleri gerçekleşti. Bütün bu devrimlerin kesişim kümesinde milliyetçilik, halkçılık, toplumculuk, kamuculuk ve etnik kaynaşma kültürü olduğu söylenebilir. Asya-Afrika-Latin Amerika’nın milletleri genlerine işlemiş olan bu değerlere dayanarak, günümüzün çok kutuplu dünyasında başı dik, özgürce yaşamak için devrimci tarihlerinden güç alıyor. Bugün, Afrika ve Asya’dan Latin Amerika’ya milli bağımsızlıkçı cereyan güçlenirken, ülkelerin kendi geçmişindeki ve dünya genelindeki devrimci atılımların mirası üzerinde şekilleniyor.",
        "Bu sayımızda, bugünü de belirleyen devrim mayasının öncülerinden, 1911 Çin Devrimi’nin önderi Sun Yat Sen’in mirasını mercek altına aldık. Büyük devrimci önder, hayata gözlerini yummasının üzerinden 100 yıl geçse de insanlığa hizmetini sürdürüyor.",
      ],
    },
    en: {
      title: "The Seed of Revolution in Asia",
      paragraphs: [
        "Over the past 25 years, the global geopolitical landscape has undergone and continues to undergo substantial transformations. The U.S.-centric system has begun its decline not only in economic terms but also in political, ideological, and cultural dimensions. Correspondingly, Asia—led primarily by China—has emerged as the world’s manufacturing powerhouse. At the same time, leading nations of the developing world have been on the rise economically.",
        "The most significant consequence of these changes is the erosion of Atlantic hegemony, which had been established after the Second World War and centered on the Europe-U.S. alliance. It has become evident that this hegemony no longer possesses the authority to dictate global processes. The “rules-based order” devised to enforce Atlantic dominance is now disintegrating. The unipolar world order, dominated by the United States following the dissolution of the Soviet Union in 1991, has ceased to exist. Today, the political strategies of the United States, Europe, and developing nations are shaped by the realities of multipolarity.",
        "While the traditional institutions that have long governed the global order are losing their influence, alternative frameworks for international cooperation—where all parties benefit mutually—are gaining strength. The nations of the developing world, uniting through initiatives such as the Belt and Road Initiative, the Shanghai Cooperation Organization, and the expanding BRICS+, are actively reshaping global dynamics. These new forms of cooperation establish a system based on “mutual respect for sovereignty and territorial integrity, non-aggression, non-interference in internal affairs, equality and mutual benefit, and peaceful coexistence.” This emerging order stands in contrast to and as an alternative to the neoliberal international system.",
        "As the first quarter of the 21st century draws to a close, the world is transforming in historical magnitude—comparable to the upheavals of a century ago. The great revolutions of the early 20th century enabled prominent Asian civilizations to rise from the ashes and shook the world. Today, Asia is once again at the forefront, but this time, it is not alone. Alongside Asia, the nations of Africa, Latin America, and the nations of the developing world are asserting their sovereignty against imperialist domination.",
        "At the dawn of the 20th century, nearly the entire world—except Türkiye, Russia, China, and Iran—was under colonial rule. The successive revolutions in Russia, Türkiye, Iran, and China served as a source of inspiration for national independence movements worldwide in their struggles against imperialism. From the mid-20th century onward, socialist-led popular revolutions also took place. These revolutionary movements shared a common ethos, embracing nationalism, populism, collectivism, publicism, and ethnic cohesion. The nations of Asia, Africa, and Latin America continue to draw strength from their revolutionary legacies, striving to live with dignity and freedom in today’s multipolar world. The momentum of national independence movements is again gaining strength across Africa, Asia, and Latin America, building upon the traditions of local and worldwide revolutionary breakthroughs.",
        "This issue focuses on the legacy of Sun Yat-sen, the leader of the 1911 Chinese Revolution and one of the pioneers of revolutionary thought, whose influence continues today. Even a century after his demise, this great revolutionary leader continues to serve humanity.",
      ],
    },
  },
  "6-3": {
    tr: {
      title: "Bandung’dan BRICS’e: Güney ülkelerinin önündeki zorlu görev",
      paragraphs: [
        "Bandung Konferansı, 2. Dünya Savaşı sonrası dönemde, “devletlerin bağımsızlık, milletlerin kurtuluş, halkların devrim” talebiyle yükselen dünya çapındaki devrim dalgasının bir parçasıydı. Bandung’da hegemonyacılığa karşı bir araya gelen Asya-Afrika ülkeleri, 1961 yılında Belgrad Zirvesi ile Bağlantısızlık Hareketi’ni kurdu. Bu hamle, o zamanki adıyla Üçüncü Dünya’daki gelişen dünya ülkelerinin uluslararası alanda bir ağırlık elde etmesini sağladı. Asya ile Afrika’da sömürgeciliğe karşı mücadelenin önemli başarılarıyla ile el ele ilerleyen bu devrimci dalganın etkisi bütün dünyada görüldü. Üçüncü dünyacılık, milli devletlerin bağımsızlığının yanı sıra yüzü sosyalizme dönük halkçı/kamucu bir sistem arayışını da içeriyordu. Daha sonraki dönemde, gelişen dünyanın milli devletleri, dünya çapında neo-liberalizmin atağı, tek kutupluluk ve 1990’lardaki küreselleşmecilik dalgasıyla emperyalizmin hücumuyla karşılaştı.",
        "Günümüzün dünyasının manzarası ise her iki dönemden de büyük ölçüde farklı. Emperyalist merkezlerde baş aşağı gidiş başlamışken, gelişen dünya ülkelerinde ise kendi milli devletine dayanarak kalkınma çabasının olumlu sonuç verdiği görülmektedir. Uluslararası alanda çok kutuplulaşmanın sağladığı olanaklar, milli devletlerin önünü açtı. Gelişen dünya ülkeleri, emperyalist tahakkümden uzaklaştıkları ölçüde, eşit ortaklar olarak birbirleriyle kurdukları ilişkilerin meyvesini toplamaya başladı.",
        "Gelişmekte olan ülkeler, Bağlantısızlar Hareketi vasıtasıyla hegemonyacılığa karşı nefes almak için güçbirliği yapmış ve birbirinden öğrenmişti. Bugün emperyalist kuzeyin karşısında kendi ulusal menfaatlerini gerçekleştirmek için güney ülkelerinin ayağa kalkışı var. Kuzey, üretimden ve insan ihtiyaçlarından kopuşun, yabancılaşmanın, bireyciliğin, ırkçılığın, sınıfsal ve cinsel ayrımcılığın kaynağını, gelişen dünya ülkeleri üzerinde tahakkümü ve özel çıkar için insan ve doğanın hiçe sayıldığı sistemi temsil ediyor. Üretim, yaratıcılık, kamusal çıkar, devletçilik, kaynaşma, ülkeler arasında eşit işbirliği, adil bir dünya ile doğa ve insan merkezli bir sistemi kurma çabası ise Güney’den yükseliyor.",
        "70. yılında Bandung Konferansı’nın temel taleplerinin geçerliliğini kouruduğu görülüyor. Fakat günümüzün farkı, gelişen dünya ülkelerin bu hedeflere ulaşabilmesi için ulusal güçlerinin ve uluslararası şartların 70 yıl öncesine göre daha elverişli olmasıdır. Güney ülkelerinin önünde, insanı ve doğayı yıkıma uğratan emperyalizm ile baş etmek için daha ileri ve kurumsallaşmış işbirliği platformları kurmak bulunuyor.",
      ],
    },
    en: {
      title: "From Bandung to BRICS: The forthcoming challenge for the Global South",
      paragraphs: [
        "The Bandung Conference was a manifestation of the worldwide revolutionary wave that rose in the post-World War II period with the demand for “independence of states, liberation of nations, revolution of peoples.” The Asian-African countries that came together against hegemonism in Bandung founded the Non-Aligned Movement with the Belgrade Summit in 1961. This initiative allowed the nations of the emerging world, then referred to as the Third World, to acquire significance worldwide. The influence of this transformative wave, coinciding with significant victories in the fight against colonialism in Asia and Africa, was seen all over the world. Third Worldism encompassed the sovereignty of nation-states and the pursuit of a populist, public-oriented system tipped toward socialism. During the subsequent period, the nation-states of the developing world confronted the assault of imperialism during the global surge of neoliberalism, unipolarity, and globalization in the 1990s.",
        "The contemporary terrain is significantly distinct from both eras. In the imperialist states, a decline has commenced, whereas in developing nations, the pursuit of development based on their nation-states is producing favorable outcomes. The opportunities afforded by multipolarity in the international sphere have facilitated the advancement of nation-states. As emerging countries have freed themselves from imperialist domination, they have started to benefit from their relationships with one another as equal partners.",
        "Through the Non-Aligned Movement, developing nations collaborated and learned from each other to resist hegemonism. Currently, the nations of the Global South are mobilizing to assert their national interests in opposition to the imperialist Global North. The North epitomizes a framework of disconnection from production and human need, alienation, individualism, racism, class and sexual discrimination, subjugation of emerging nations, and a neglect for humanity and nature in pursuit of private interest. Production, innovation, public interest, a public-driven economy, cohesion, equitable collaboration among nations, a just world, and the endeavor to create a nature- and human-centered system are emerging from the South.",
        "In its 70th year, the fundamental demands of the Bandung Conference remain pertinent. Today, the national strengths and international conditions are more conducive for developing countries to attain these goals than they were 70 years ago. The imperative for Southern nations is to establish more sophisticated and institutionalized cooperative frameworks to counteract imperialism, which is detrimental to both humanity and nature.",
      ],
    },
  },
  "6-4": {
    tr: {
      title: "Birlikte kalkınmak için ortak güvenlik",
      paragraphs: [
        "Üç kötülük: Terörizm, ayrılıkçılık ve dinci aşırıcılık… Kendi başlarına farklı dönemlerde ortaya çıksalar da birlikte üçlü bir paket program olarak emperyalizm tarafından, gelişen dünya milletlerinin önüne engel olarak çıkarılmıştır. “Üç kötülük”, 20’nci yüzyıl boyunca gelişen dünyadaki milli bütünleşmeyi ve kaynaşmayı engellemek için emperyalizmin silahı olarak işlev görmüştür.",
        "Dahası, emperyalizm terörizmin tanımını da ters yüz etmiştir: Emperyalizme karşı milli kurtuluş savaşları ve halk devrimleri terörizm olarak damgalanırken, milli devletlere karşı savaşan köktendinci ve ayrılıkçı terör örgütleri, “özgürlük savaşçıları” olarak sunulmuştur. Bu örgütler ya doğrudan emperyalizm tarafından kurulmuş ya da desteklenerek palazlandırılmıştır.",
        "Mustafa Kemal Atatürk, Nkrumah, Nasır, Gandhi, Nehru, Mao Zedung, Sukarno ve diğer halk devrimi önderleri, emperyalizme göre teröristtir. Emperyalist merkezlerde, bugün de hegemonyacılığa karşı kendi milli devletini koruyan eylemleri uygulayan liderler, otokrat olarak nitelenmektedir.",
        "Buna karşılık, “dini özgürlükler” ya da “etnik haklar” bahanesiyle milli devletlere karşı savaşan ayrılıkçı ya da köktendinci terör örgütleri doğrudan emperyalizm tarafından desteklenmektedir. Türkiye’de ve Suriye’de PKK, Çin’de Doğu Türkistan İslami Hareketi (yeni adıyla Türkistan İslam Partisi), İran’da Cundullah, Pakistan’da Tehrik-i Taliban Pakistan ve Belucistan Kurtuluş Örgütü, Afganistan ve Orta Asya’da IŞİD Horasan, Özbekistan İslami Hareketi, Nijerya’da Beko Haram vb. gibi Asya ve Afrika’da faaliyet gösteren örgütler, etnik ayrılıkçılık ve/veya dinci aşırıcılık temelinde terör eylemleriyle, bulundukları bölgelerde emperyalizmin güdümünde faaliyet göstermektedir. Emperyalizm, böylece, gelişen dünya devletlerinin güç ve imkanlarını tüketmekte, istikrarsızlaşan bölgeye müdahil olmak için uygun bahaneyi yaratmaktadır. Aynı zamanda gelişen dünyaya, “etnik ve dini hakların korunması” iddiasıyla, esas amacı milli devletleri parçalamak olan, milli bütünleşmeyi ve milli devlet yapısını zayıflatan adem-i merkeziyetçi siyasal programları dayatmaktadır.",
        "“Üç kötülüğün” panzehiri, çok kutupluluğun gelişmesidir. Nitekim, dünyanın en büyük terör örgütlerinden biri olan PKK, çok kutupluluğun bir zaferi olarak silah bırakmak zorunda kalmıştır. Oluşan iklim, diğer terör örgütlerinin de silah bırakmasına, böylece etnik veya dinci aşırılıkçılığın hedef kitlesi olan unsurların kendi milletleri ve devletleri ile bütünleşmesine imkan sağlamaktadır.",
        "Emperyalist hegemonyacılığın bu siyasal ve ideolojik programının karşısında, gelişen dünyanın çözümü ise güvenlik işbirliğini geliştirmek olmaktadır. 1990’ların ikinci yarısından sonra temeli atılan Şanghay İşbirliği Örgütü’nün “üç kötülüğe karşı mücadele” şiarıyla başlattığı güvenlik işbirliğinin, kendisinden önceki benzer platformlarından çok önemli bir farkı bulunmaktadır: Aynı tehditlerin hedefinde yer alan ülkeler, ortak güvenliği sağlamak için ortak kalkınmayı esas alan bir işbirliği hedefinde buluşmuştur, buluşmaktadır. Ortak kalkınmaya dayalı bir işbirliği, gelişen dünya devletlerinin, birbirleriyle girdikleri kısır ve dar rekabetçi mücadelelerle gücünü tüketmesi yerine, birlikte güçlenmesini sağlamaktadır. Böylelikle, emperyalizmin gelişen dünya ülkeleri arasındaki sorunlara burnunu sokması da engellenmektedir.",
        "Şanghay İşbirliği Örgütü’nün başarıyla uyguladığı bu modeldeki ana yaklaşım, bölgesel ve küresel ölçekte güvenlik işbirliğinin anahtarı haline gelmektedir. Bu model, günümüzün çok kutupluluk ortamında gelişen dünya ülkelerinin en önemli işbirliği yapısı olarak genişleyen ve güçlenen BRICS içinde de giderek kurumsallaşmaktadır.",
      ],
    },
    en: {
      title: "Common security for shared development",
      paragraphs: [
        "Three evils: terrorism, separatism, and religious extremism… Although they emerged in different periods on their own, they collectively constituted a triple package program devised by imperialism to impede the progress of developing nations. Throughout the 20th century, the “three evils” served as instruments of imperialism to obstruct national unification and cohesion in the emerging nations. Furthermore, imperialism has inverted the meaning of terrorism: National liberation wars and popular revolutions against imperialism were labeled as terrorism, whereas fundamentalist and separatist terrorist groups combating national states were characterized as “freedom fighters.” These organizations were either established directly by imperialism or endorsed and cultivated by it.",
        "According to imperialism, Mustafa Kemal Atatürk, Nkrumah, Nasser, Gandhi, Nehru, Mao Zedong, Sukarno, and other leaders of the people’s revolution are classified as terrorists. In the imperialist centers, contemporary leaders who undertake measures to save their nation from hegemonism are labeled as autocrats.",
        "Conversely, separatist or religious extremist terrorist organizations that oppose national states under the guise of “religious freedoms” or “ethnic rights” receive direct support from imperialism. Entities functioning in Asia and Africa, including the PKK in Turkey and Syria, the East Turkistan Islamic Movement (currently referred to as the Turkistan Islamic Party) in China, Jundullah in Iran, Tehrik-i Taliban Pakistan and the Baluchistan Liberation Army in Pakistan, ISIS Khorasan in Afghanistan and Central Asia, the Islamic Movement of Uzbekistan, and Boko Haram in Nigeria, execute operations under the auspices of imperialism in their respective territories, engaging in terrorist activities rooted in ethnic separatism and/or religious extremism.",
        "Imperialism thus diminishes the national power and resources of developing nations, providing a handy justification for intervention in destabilized areas. Simultaneously, under the guise of “safeguarding ethnic and religious rights,” it enforces decentralized political agendas on developing nations, undermining national unity and state structures, primarily aimed at fragmenting its national states.",
        "The remedy for the “three evils” is the advancement of multipolarity. Indeed, the PKK, among the largest terrorist organizations globally, was compelled to disarm as a victory of multipolarity. The established climate permits other terrorist organizations to disarm, thus enabling the target groups of ethnic or religious extremism to integrate with their nations and states.",
        "In response to this political and ideological program of imperialist hegemony, the solution for the developing world is to develop security cooperation. The security collaboration established by the Shanghai Cooperation Organization, which started out in the latter half of the 1990s under the banner of “the fight against the three evils,” possesses a significant distinction from preceding platforms: Countries facing the same threats have convened and continue to convene for collaboration centered on shared development to guarantee collective security. Collaboration centered on shared development empowers emerging nations to strengthen together rather than depleting their resources through vicious and detrimental rivalry among themselves. This strategy prevents imperialism from interfering in the issues of developing nations.",
        "This model’s primary strategy, well executed by the Shanghai Cooperation Organization, is emerging as a crucial element for security collaboration at both regional and global levels. This strategy is progressively being institutionalized within the BRICS, which is expanding and fortifying as the preeminent cooperative framework for emerging nations in the contemporary multipolar landscape.",
      ],
    },
  },
  "7-1": {
    tr: {
      title: "Yeşil çözümler Küresel Güney’den yükseliyor",
      paragraphs: [
        "Birçok farklı uluslararası bilimsel kurumun yaptığı hesaplamalara göre, önümüzdeki 25 yıl içinde dünyada çok ciddi bir su krizi ve aynı zamanda buna bağlı olarak gıda kıtlığı yaşanması bekleniyor. Konu, temel meselelerde ortak anlayış ve uluslararası ilişkilerde bir düzen sağlamak amacıyla faaliyet gösteren Birleşmiş Milletler’in yanı sıra çok sayıda farklı küresel ve bölgesel ölçekli kuruluşun gündeminde. Toplantılar yapılıyor, kararlar alınıyor. Fakat, insanlığın geleceğini tehdit eden bu devasa meseleye karşı tüm dünya halklarının ortak çıkarını gözeten somut ve uygulanabilir bir çözüm ortaya konamıyor. Dahası, bu toplantılarda alınan kararlar, bugün uluslararası sistemdeki eşitsizlik nedeniyle gelişmekte olan ülkelerin aleyhine sonuçlara yol açmaktadır.",
        "Batı merkezci gözlükler çıkarılarak yapılacak nesnel bir analizde bugün dünyanın karşı karşıya olduğu krizin asıl sorumlusunun, özel kâr ve çıkar için doğayı yıkıma uğratan gelişmiş ülkelerin yönetimindeki sistem olduğu açıkça görülecektir. Bilimsel hesaplamalara göre, sanayi devriminden bugüne küresel ısınmaya neden olan sera gazı salımlarının esası gelişmiş ülkelerden kaynaklanmıştır. Ancak bunun sonuçlarından en fazla etkilenenlerin ise gelişmekte olan ülkeler olduğu görülmektedir. Bu sonuç üzerinden düşünülecek olursa, elini en fazla taşın altına koyması gereken, Küresel Kuzey’in gelişmiş ülkeleridir. Oysa Küresel Kuzey, bu krizin yükünü Küresel Güney’in üstüne yıkmaya çalışmaktadır.",
        "Gerçekte, çözüm insan ve doğa arasındaki uyumu hedefleyen bir anlayışla ve tüm insanlığın ortak yararını temel alarak bulunabilecektir. Dünyanın karşı karşıya olduğu diğer sorunlar gibi tüm insanlığı tehdit eden bu meselede de çözüm pratikleri gelişen dünyadan yükselmektedir. Gelişmekte olan devletler, BRICS, Şanghay İşbirliği Örgütü ile Kuşak ve Yol Girişimi’nin başını çektiği Küresel Güney’in işbirliği platformları kapsamında son 10 yılda yeşil, düşük karbonlu kalkınma için işbirliğini ilerletmektedir. Küresel Güney’in milli devletleri bu işbirliği platformları vasıtasıyla yeni bir anlayışla bir araya gelmektedir. Neo-liberal ekonomik ve siyasal uluslararası düzenin tıkandığı verili koşullarda, gelişen dünya devletleri ortak kalkınma temelinde buluşmaktadır. Aynı zamanda dış borca dayalı finansmana ve serbest piyasaya dayanan ekonomik modelin yerine, iç pazara ve üretime dayanan halkçı ve kamucu seçeneğin zemini güçlenmektedir. Bu anlayış temelinde buluşan Küresel Güney ülkeleri, emperyalist dayatmalara karşı “yeşil endüstri” için birbirleriyle daha fazla işbirliğine giderek, insanlığın ortak geleceğini inşa etme yolunda ilerlemektedir. Aslında durumu, “Küresel Kuzey yıkım, Küresel Güney çözüm getiriyor” diye nitelemek mümkündür.",
      ],
    },
    en: {
      title: "Green solutions are emerging from the Global South",
      paragraphs: [
        "Various international scientific institutions have projected that a severe water crisis and subsequent food shortages worldwide are likely to occur within the next 25 years. This issue is on the agenda of the United Nations, which aims to establish a common understanding of fundamental issues and maintain international order, as well as numerous other global and regional organizations. Meetings are held and decisions are made. However, no feasible, concrete solution that serves the common interests of all peoples against this enormous threat to humanity’s future has yet been put forward. Furthermore, the decisions made at these meetings disadvantage developing countries due to current inequalities in the international system.",
        "The crisis facing the world today is best understood by looking beyond Western-centric viewpoints and conducting an objective analysis. It becomes clear that the real culprit behind the crisis facing the world today is the system run by developed countries that destroys nature for private profit and gain. According to scientific calculations, the majority of greenhouse gas emissions that have caused global warming since the Industrial Revolution have originated in developed countries. However, it is developing countries that are most affected by the consequences. Given this, it is the developed countries of the Global North that should bear the most significant responsibility. Yet the Global North is attempting to shift the burden of this crisis onto the Global South.",
        "In fact, the solution lies in an approach that aims to achieve harmony between humans and nature, based on the common good of all humanity. As with other global issues, solutions to this problem, which threatens humanity as a whole, are emerging from the developing world. Over the past decade, developing countries have been advancing cooperation for green, low-carbon development within the Global South cooperation platforms, led by the BRICS, the Shanghai Cooperation Organization, and the Belt and Road Initiative. Nation-states in the Global South are uniting under a new understanding through these cooperation platforms. Given the stalling of the neoliberal economic and political international order, developing world states are converging based on shared development goals. At the same time, the groundwork is being laid for an alternative model based on domestic markets and production that will replace the current system of external debt financing and free markets. By coming together on this basis, Global South countries are advancing towards building a common future for humanity, increasing their cooperation for a ‘green industry’, and resisting imperialist impositions. Indeed, the situation can be summarized as ‘the Global North brings destruction; the Global South brings solutions.’",
      ],
    },
  },
  "7-2": {
    tr: {
      title: "İnsanlığın Geleceği İçin Büyük Tecrübe",
      subtitle: "Çin’e Özgü Sosyalizmin Ekonomi Politiği",
      paragraphs: [
        "1949’da kurulan Çin Halk Cumhuriyeti’nin olağanüstü gelişmesini mümkün kılan dinamikler, günümüzde dünya genelinde en çok tartışılan konular arasında yer almaktadır. Çin Komünist Partisi önderliğinde Çin halkının sosyalizmi inşa sürecinde edindiği tarihsel tecrübe, bilimsel olarak incelenmesi gereken özgün ve benzersiz bir örnek sunmaktadır. Yirmi birinci yüzyılda dünyanın en hızlı büyüyen ekonomilerinden biri hâline gelen Çin, aynı zamanda hegemonik güçlerin küresel tahakkümünü sınırlayan bir rol oynamaktadır. Bununla birlikte, halkın yaşam standartlarını yükselten sosyalist sistemiyle, neoliberal küreselleşme anlayışına ve kapitalist serbest piyasa modeline karşı güçlü bir alternatif olarak öne çıkmaktadır. Bu bağlamda, Çin’deki sistemin niteliğini belirleyen temel unsurları, özellikle politik ekonomi perspektifinden, önyargılardan ve dogmatik yaklaşımlardan uzak bir biçimde incelemek temel bir görev olarak karşımızda durmaktadır.",
        "Başlangıç noktası olarak şu sorular sorulabilir:",
        "• Tarihsel örnekler dikkate alındığında, sosyalizmin kuruluş sürecindeki aşamalar nasıl kavranmalıdır? Bir ülkede sosyalist iktidarın ve sosyalist inşanın sürekliliğini belirleyen ölçütler nelerdir? Uzun bir inşa sürecinden geçtiğini ifade eden Çin, bu çerçevede hangi aşamada bulunmaktadır?",
        "• Çin’in uyguladığı “sosyalist piyasa ekonomisi” modeli, ortaya çıkardığı sonuçlarla birlikte nasıl değerlendirilmelidir? Piyasa ile sosyalizm birbirini dışlayan kategoriler midir? Geçmiş ve güncel sosyalizm deneyimleri dikkate alındığında, piyasanın sosyalist inşa sürecinde bir araç olarak kullanılması nasıl yorumlanmalıdır?",
        "• Çin’in dünya kapitalist-emperyalist sistemi içindeki ve karşısındaki özgül konumu ve çelişkileri nasıl kavramsallaştırılmalıdır?",
        "• Çin’in ekonomik, toplumsal ve uluslararası alandaki başarılarının hem Çin’e özgü hem de tüm insanlığı ilgilendiren boyutları bulunmaktadır. Dünyanın ve özellikle Türkiye’nin kendi kalkınma yollarını oluştururken Çin deneyiminden çıkarabileceği temel dersler nelerdir?",
        "BRIQ’in bu sayısında, bu sorulara yanıt arayan, Çin’in eski kuşak tanınmış politik ekonomistlerinden Prof. Dr. He Ganqiang ile Prof. Dr. Xinhua Jian’a ait iki önemli çalışma yayımlanmaktadır. Prof. Dr. He’nin Çin’deki sosyalist piyasa ekonomisi uygulamalarını içeriden ve eleştirel bir perspektifle değerlendirdiği Çince makalesi ile Prof. Dr. Xinhua’nın Çince yayımlanmış Çin’e Özgü Sosyalist Politik Ekonomide Başlıca ve Zor Sorunlar Üzerine İnceleme adlı kitabının giriş bölümünün çevirisi.",
        "Prof. Dr. He ve Prof. Dr. Xinhua, ilk yıllarından itibaren Çin Devrimi’nin öncü kuşağı içinde yer almış, iki önemli tarihsel kişilik. Tarım ve fabrika işçiliğinden akademisyenliğe uzanan yaşam serüvenleri boyunca Çin Devrimi’nin bütün kritik dönüm noktalarına tanıklık etmiş ve dönemin temel tartışmalarının aktif özneleri olmuşlardır. Bu çalışmaların, söz konusu meseleye ilişkin yürütülen kuramsal ve siyasal tartışmalara önemli katkılar sunacağı düşünülmektedir.",
        "BRIQ olarak, başta Türkiye olmak üzere dünya genelindeki politik ekonomistleri, yukarıda ana hatları çizilen çerçeve dâhilinde çalışmalar üretmeye davet ediyor; bu alandaki nitelikli ve özgün araştırmalara dergimizin sayfalarını açıyoruz.",
      ],
    },
    en: {
      title: "A Significant Experience for the Future of Humanity",
      subtitle: "The Political Economy of Socialism with Chinese Characteristics",
      paragraphs: [
        "The political economy underlying the People’s Republic of China’s development trajectory since its founding in 1949 remains one of the most widely analyzed issues in contemporary scholarship. The experience of socialist construction under the leadership of the Communist Party of China constitutes a distinctive case that warrants systematic and rigorous academic analysis.",
        "In the twenty-first century, China has emerged as one of the world’s leading economies and has played an increasingly significant role in shaping global economic and political dynamics. Its development model, described as ‘socialism with Chinese characteristics,’ has also rekindled discussion of alternatives to the dominant patterns of market-led development and neoliberal globalization. These developments underscore the importance of examining the structural features of China’s system from a political economy perspective, avoiding both normative bias and reductionist interpretations.",
        "Against this background, several key questions arise:",
        "• How should the stages of socialist construction be conceptualized in light of historical and comparative experiences? What criteria determine the sustainability of socialist political authority and the continuity of socialist-oriented development? Within this framework, how should China’s current developmental stage be assessed?",
        "• How should China’s ‘socialist market economy’ be evaluated in relation to its institutional structure and outcomes? To what extent are market mechanisms compatible with socialist development, particularly when considered in light of both historical and contemporary experiences?",
        "• How should China’s position within the global capitalist system—and its points of tension and interaction with that system—be theoretically conceptualized?",
        "• To what extent do China’s economic and social transformations offer insights of broader relevance? What lessons, if any, can be drawn for other countries, including Türkiye, in terms of development strategies and institutional design?",
        "Two Chinese contributions that explicitly address these issues are presented in this issue by BRIQ: an academic piece by Prof. Dr. He Ganqiang and a chapter translated from a Chinese-language book by Prof. Dr. Xinhua Jian, two well-known Marxist political economists. Both academics have a wealth of experience in political economy and have made significant contributions to discussions of China’s socialist development.",
        "It is anticipated that these contributions will enrich ongoing theoretical and empirical discussions in the field. BRIQ therefore invites political economists in Türkiye and internationally to engage with these issues and to contribute original, high-quality research within this broad analytical framework.",
      ],
    },
  },
  "7-3": {
    tr: {
      title: "Kültürel Miras Yağması ve Emperyalist Hegemonya",
      paragraphs: [
        "İnsanlığın kuşaklar boyunca inşa ettiği medeniyetlerin somut taşıyıcısı olan kültürel mirasın ait olduğu coğrafyalardan koparılması, yalnızca bir suç değil, uluslararası sistemin adaletsizliğinin en sert tezahürlerinden biridir. Kültürel varlıkların çalınması ve başka merkezlere taşınması, özellikle sömürgecilik döneminde sistematik bir nitelik kazanmış; “keşif”, “koruma” ve “bilim” söylemleri altında yürütülen bu süreç, gerçekte emperyalist tahakkümün kültürel boyutunu oluşturmuştur. Bu yağma, yalnızca fiziksel bir transfer değil, aynı zamanda tarihin yeniden yazılmasıdır. Ezilen dünyanın kendi geçmişinden koparılmasıyla, Batı merkezli tarih anlatısı ve “medeniyet üstünlüğü” safsatası inşa edilmiştir.",
        "Bugün Batı başkentlerindeki müzeler, Asya, Afrika, Güney Amerika ve dünyanın diğer bölgelerinden taşınmış yüz binlerce eseri barındırmaktadır. Bununla birlikte, gelişen dünyadan çalınan kültürel varlıkların önemli bir bölümü müzayede evlerinde yüksek fiyatlarla el değiştirmekte ya da özel koleksiyonlarda tutulmaktadır. Küresel sanat piyasasının büyümesiyle birlikte bu akış daha da karmaşık hale gelmiş; yerel kazılardan uluslararası galerilere uzanan çok katmanlı bir kaçakçılık zinciri ortaya çıkmıştır. Bu zincirde eserler, sahte köken belgeleriyle “temizlenerek” yasal dolaşıma sokulmaktadır.",
        "Soğuk Savaş sonrası dönemde ve özellikle son yirmi yılda, kültürel miras yağması yeni bir ivme kazanmıştır. ABD’nin Afganistan ve Irak işgalleri ile 2011 sonrasında Suriye’ye yönelik parçalama operasyonları, emperyalist müdahalelerin kültürel varlıklar üzerinde ne denli yıkıcı sonuçlar doğurduğunu açıkça göstermiştir. Siyasi istikrarsızlık ve çatışma ortamlarında artan yasadışı kazılar, bu eserleri yalnızca küresel piyasaya taşımakla kalmamakta, aynı zamanda terör örgütleri ve organize suç ağları için önemli bir finansman kaynağı oluşturmaktadır. Mevcut veriler, bu alanın yıllık hacminin yüz milyonlarca dolardan birkaç milyar dolara kadar uzanan geniş bir aralıkta seyrettiğini göstermektedir.",
        "Bu tablo karşısında, kültürel varlıkların korunması ve iadesi meselesi, gelişen dünya ülkeleri için yalnızca bir kültür politikası değil, aynı zamanda egemenlik ve tarihsel adalet meselesidir. İade süreçleri, geçmişin telafisine yönelik sembolik adımlar olmanın ötesinde, uluslararası sistemde güvenin yeniden inşası açısından da kritik önemdedir. Ancak mevcut hukuki mekanizmalar ve uluslararası sözleşmeler sınırlı kalmaktadır.",
        "Sonuç olarak, kültürel mirasın yağmalanması insanlığın ortak hafızasına yönelmiş bir tehdittir. Bu nedenle mesele, tek tek ülkelerin değil, bütün ülkelerin ortak sorumluluğu olarak ele alınmalıdır. Bununla birlikte, yağmanın esas olarak gelişen dünyayı hedef aldığı ve eserlerin büyük ölçüde emperyalist merkezlerde toplandığı göz önüne alındığında, gelişen dünya ülkeleri arasındaki işbirliği bu alandaki mücadelenin güçlendirilmesi açısından belirleyici olacaktır. Kültürel varlıkların korunması ve iadesi için yürütülecek mücadele, kültürel geçmişine sahip çıkmanın yanı sıra daha adil, dengeli ve çok taraflı bir uluslararası düzenin inşasına katkı sunmak anlamına gelmektedir.",
      ],
    },
    en: {
      title: "The Plunder of Cultural Heritage and Imperialist Hegemony",
      paragraphs: [
        "The removal of cultural heritage, the tangible carrier of civilizations built by humanity over generations, from its places of origin is not merely a crime, but one of the most striking manifestations of injustice in the international system. The theft and transfer of cultural assets to distant centers acquired a systematic character, particularly during the colonial period. Conducted under the rhetoric of ‘discovery,’ ‘protection,’ and ‘science,’ this process in reality constituted the cultural dimension of imperial domination. Such plunder represents not only a physical displacement but also a rewriting of history itself. By severing the oppressed world from its own past, a Western-centric historical narrative has been constructed, along with the fallacy of ‘civilizational superiority.’",
        "Today, museums in Western capitals house hundreds of thousands of artifacts removed from Asia, Africa, South America, and other parts of the world. At the same time, a significant portion of cultural objects looted from the developing world circulates through auction houses at exorbitant prices or remains in private collections. With the expansion of the global art market, these flows have become increasingly complex, giving rise to multi-layered trafficking networks extending from local excavations to international galleries. Within this chain, artifacts are laundered into the legal market through fabricated provenance records.",
        "In the post–Cold War period, and especially over the past two decades, the looting of cultural heritage has gained renewed momentum. The U.S. invasions of Afghanistan and Iraq, along with the post-2011 operations aimed at fragmenting Syria, have clearly demonstrated the devastating impact of imperial interventions on cultural assets. In conditions of political instability and armed conflict, the increase in illicit excavations not only feeds global markets but also provides a significant source of financing for terrorist organizations and organized crime networks. Available estimates suggest that the annual scale of this illicit trade ranges from hundreds of millions to several billion dollars.",
        "In this context, the protection and restitution of cultural property are not merely matters of cultural policy for developing countries, but also of sovereignty and historical justice. Restitution processes go beyond symbolic acts of redress and are critical for rebuilding trust within the international system. However, existing legal frameworks and international conventions remain insufficient.",
        "Ultimately, the looting of cultural heritage constitutes a threat to the shared memory of humanity. It must therefore be addressed not as the responsibility of individual states alone, but as a collective responsibility of all countries. At the same time, given that this plunder disproportionately targets the developing world while the artifacts are largely concentrated in imperial centers, cooperation among developing countries will be decisive in strengthening this struggle. Efforts to protect and reclaim cultural property are not only about preserving the past, but also about contributing to the construction of a more just, balanced, and multilateral international order.",
      ],
    },
  },
};
