export type EditorialCopy = {
  title: string;
  subtitle?: string;
  paragraphs: string[];
};

type LocalizedEditorial = {
  tr: EditorialCopy;
  en: EditorialCopy;
};

export const archivedEditorials: Record<string, LocalizedEditorial> = {
  "7-1": {
    tr: {
      title: "Yeşil çözümler Küresel Güney’den yükseliyor",
      paragraphs: [
        "Birçok farklı uluslararası bilimsel kurumun yaptığı hesaplamalara göre, önümüzdeki 25 yıl içinde dünyada çok ciddi bir su krizi ve aynı zamanda buna bağlı olarak gıda kıtlığı yaşanması bekleniyor. Konu, temel meselelerde ortak anlayış ve uluslararası ilişkilerde bir düzen sağlamak amacıyla faaliyet gösteren Birleşmiş Milletler’in yanı sıra çok sayıda farklı küresel ve bölgesel ölçekli kuruluşun gündeminde. Toplantılar yapılıyor, kararlar alınıyor. Fakat, insanlığın geleceğini tehdit eden bu devasa meseleye karşı tüm dünya halklarının ortak çıkarını gözeten somut ve uygulanabilir bir çözüm ortaya konamıyor. Dahası, bu toplantılarda alınan kararlar, bugün uluslararası sistemdeki eşitsizlik nedeniyle gelişmekte olan ülkelerin aleyhine sonuçlara yol açmaktadır.",
        "Batı merkezci gözlükler çıkarılarak yapılacak nesnel bir analizde bugün dünyanın karşı karşıya olduğu krizin asıl sorumlusunun, özel kâr ve çıkar için doğayı yıkıma uğratan gelişmiş ülkelerin yönetimindeki sistem olduğu açıkça görülecektir. Bilimsel hesaplamalara göre, sanayi devriminden bugüne küresel ısınmaya neden olan sera gazı salımlarının esası gelişmiş ülkelerden kaynaklanmıştır. Ancak bunun sonuçlarından en fazla etkilenenlerin ise gelişmekte olan ülkeler olduğu görülmektedir. Bu sonuç üzerinden düşünülecek olursa, elini en fazla taşın altına koyması gereken, Küresel Kuzey’in gelişmiş ülkeleridir. Oysa Küresel Kuzey, bu krizin yükünü Küresel Güney’in üstüne yıkmaya çalışmaktadır.",
        "Gerçekte, çözüm insan ve doğa arasındaki uyumu hedefleyen bir anlayışla ve tüm insanlığın ortak yararını temel alarak bulunabilecektir. Dünyanın karşı karşıya olduğu diğer sorunlar gibi tüm insanlığı tehdit eden bu meselede de çözüm pratikleri gelişen dünyadan yükselmektedir. Gelişmekte olan devletler, BRICS, Şanghay İşbirliği Örgütü ile Kuşak ve Yol Girişimi’nin başını çektiği Küresel Güney’in işbirliği platformları kapsamında son 10 yılda yeşil, düşük karbonlu kalkınma için işbirliğini ilerletmektedir. Küresel Güney’in milli devletleri bu işbirliği platformları vasıtasıyla yeni bir anlayışla bir araya gelmektedir. Neo-liberal ekonomik ve siyasal uluslararası düzenin tıkandığı verili koşullarda, gelişen dünya devletleri ortak kalkınma temelinde buluşmaktadır. Aynı zamanda dış borca dayalı finansmana ve serbest piyasaya dayanan ekonomik modelin yerine, iç pazara ve üretime dayanan halkçı ve kamucu seçeneğin zemini güçlenmektedir. Bu anlayış temelinde buluşan Küresel Güney ülkeleri, emperyalist dayatmalara karşı “yeşil endüstri” için birbirleriyle daha fazla işbirliğine giderek, insanlığın ortak geleceğini inşa etme yolunda ilerlemektedir. Aslında durumu, “Küresel Kuzey yıkım, Küresel Güney çözüm getiriyor” diye nitelemek mümkündür.",
      ],
    },
    en: {
      title: "Green solutions are emerging from the Global South",
      paragraphs: [
        "Various international scientific institutions have projected that a severe water crisis and subsequent food shortages worldwide are likely to occur within the next 25 years. This issue is on the agenda of the United Nations, which aims to establish a common understanding of fundamental issues and maintain international order, as well as numerous other global and regional organizations. Meetings are held and decisions are made. However, no feasible, concrete solution that serves the common interests of all peoples against this enormous threat to humanity’s future has yet been put forward. Furthermore, the decisions made at these meetings disadvantage developing countries due to current inequalities in the international system.",
        "The crisis facing the world today is best understood by looking beyond Western-centric viewpoints and conducting an objective analysis. It becomes clear that the real culprit behind the crisis facing the world today is the system run by developed countries that destroys nature for private profit and gain. According to scientific calculations, the majority of greenhouse gas emissions that have caused global warming since the Industrial Revolution have originated in developed countries. However, it is developing countries that are most affected by the consequences. Given this, it is the developed countries of the Global North that should bear the most significant responsibility. Yet the Global North is attempting to shift the burden of this crisis onto the Global South.",
        "In fact, the solution lies in an approach that aims to achieve harmony between humans and nature, based on the common good of all humanity. As with other global issues, solutions to this problem, which threatens humanity as a whole, are emerging from the developing world. Over the past decade, developing countries have been advancing cooperation for green, low-carbon development within the Global South cooperation platforms, led by the BRICS, the Shanghai Cooperation Organization, and the Belt and Road Initiative. Nation-states in the Global South are uniting under a new understanding through these cooperation platforms. Given the stalling of the neoliberal economic and political international order, developing world states are converging based on shared development goals. At the same time, the groundwork is being laid for an alternative model based on domestic markets and production that will replace the current system of external debt financing and free markets. By coming together on this basis, Global South countries are advancing towards building a common future for humanity, increasing their cooperation for a ‘green industry’, and resisting imperialist impositions. Indeed, the situation can be summarized as ‘the Global North brings destruction; the Global South brings solutions.’",
      ],
    },
  },
  "7-2": {
    tr: {
      title: "İnsanlığın Geleceği İçin Büyük Tecrübe",
      subtitle: "Çin’e Özgü Sosyalizmin Ekonomi Politiği",
      paragraphs: [
        "1949’da kurulan Çin Halk Cumhuriyeti’nin olağanüstü gelişmesini mümkün kılan dinamikler, günümüzde dünya genelinde en çok tartışılan konular arasında yer almaktadır. Çin Komünist Partisi önderliğinde Çin halkının sosyalizmi inşa sürecinde edindiği tarihsel tecrübe, bilimsel olarak incelenmesi gereken özgün ve benzersiz bir örnek sunmaktadır. Yirmi birinci yüzyılda dünyanın en hızlı büyüyen ekonomilerinden biri hâline gelen Çin, aynı zamanda hegemonik güçlerin küresel tahakkümünü sınırlayan bir rol oynamaktadır. Bununla birlikte, halkın yaşam standartlarını yükselten sosyalist sistemiyle, neoliberal küreselleşme anlayışına ve kapitalist serbest piyasa modeline karşı güçlü bir alternatif olarak öne çıkmaktadır. Bu bağlamda, Çin’deki sistemin niteliğini belirleyen temel unsurları, özellikle politik ekonomi perspektifinden, önyargılardan ve dogmatik yaklaşımlardan uzak bir biçimde incelemek temel bir görev olarak karşımızda durmaktadır.",
        "Başlangıç noktası olarak şu sorular sorulabilir:",
        "• Tarihsel örnekler dikkate alındığında, sosyalizmin kuruluş sürecindeki aşamalar nasıl kavranmalıdır? Bir ülkede sosyalist iktidarın ve sosyalist inşanın sürekliliğini belirleyen ölçütler nelerdir? Uzun bir inşa sürecinden geçtiğini ifade eden Çin, bu çerçevede hangi aşamada bulunmaktadır?",
        "• Çin’in uyguladığı “sosyalist piyasa ekonomisi” modeli, ortaya çıkardığı sonuçlarla birlikte nasıl değerlendirilmelidir? Piyasa ile sosyalizm birbirini dışlayan kategoriler midir? Geçmiş ve güncel sosyalizm deneyimleri dikkate alındığında, piyasanın sosyalist inşa sürecinde bir araç olarak kullanılması nasıl yorumlanmalıdır?",
        "• Çin’in dünya kapitalist-emperyalist sistemi içindeki ve karşısındaki özgül konumu ve çelişkileri nasıl kavramsallaştırılmalıdır?",
        "• Çin’in ekonomik, toplumsal ve uluslararası alandaki başarılarının hem Çin’e özgü hem de tüm insanlığı ilgilendiren boyutları bulunmaktadır. Dünyanın ve özellikle Türkiye’nin kendi kalkınma yollarını oluştururken Çin deneyiminden çıkarabileceği temel dersler nelerdir?",
        "BRIQ’in bu sayısında, bu sorulara yanıt arayan, Çin’in eski kuşak tanınmış politik ekonomistlerinden Prof. Dr. He Ganqiang ile Prof. Dr. Xinhua Jian’a ait iki önemli çalışma yayımlanmaktadır. Prof. Dr. He’nin Çin’deki sosyalist piyasa ekonomisi uygulamalarını içeriden ve eleştirel bir perspektifle değerlendirdiği Çince makalesi ile Prof. Dr. Xinhua’nın Çince yayımlanmış Çin’e Özgü Sosyalist Politik Ekonomide Başlıca ve Zor Sorunlar Üzerine İnceleme adlı kitabının giriş bölümünün çevirisi.",
        "Prof. Dr. He ve Prof. Dr. Xinhua, ilk yıllarından itibaren Çin Devrimi’nin öncü kuşağı içinde yer almış, iki önemli tarihsel kişilik. Tarım ve fabrika işçiliğinden akademisyenliğe uzanan yaşam serüvenleri boyunca Çin Devrimi’nin bütün kritik dönüm noktalarına tanıklık etmiş ve dönemin temel tartışmalarının aktif özneleri olmuşlardır. Bu çalışmaların, söz konusu meseleye ilişkin yürütülen kuramsal ve siyasal tartışmalara önemli katkılar sunacağı düşünülmektedir.",
        "BRIQ olarak, başta Türkiye olmak üzere dünya genelindeki politik ekonomistleri, yukarıda ana hatları çizilen çerçeve dâhilinde çalışmalar üretmeye davet ediyor; bu alandaki nitelikli ve özgün araştırmalara dergimizin sayfalarını açıyoruz.",
      ],
    },
    en: {
      title: "A Significant Experience for the Future of Humanity",
      subtitle: "The Political Economy of Socialism with Chinese Characteristics",
      paragraphs: [
        "The political economy underlying the People’s Republic of China’s development trajectory since its founding in 1949 remains one of the most widely analyzed issues in contemporary scholarship. The experience of socialist construction under the leadership of the Communist Party of China constitutes a distinctive case that warrants systematic and rigorous academic analysis.",
        "In the twenty-first century, China has emerged as one of the world’s leading economies and has played an increasingly significant role in shaping global economic and political dynamics. Its development model, described as ‘socialism with Chinese characteristics,’ has also rekindled discussion of alternatives to the dominant patterns of market-led development and neoliberal globalization. These developments underscore the importance of examining the structural features of China’s system from a political economy perspective, avoiding both normative bias and reductionist interpretations.",
        "Against this background, several key questions arise:",
        "• How should the stages of socialist construction be conceptualized in light of historical and comparative experiences? What criteria determine the sustainability of socialist political authority and the continuity of socialist-oriented development? Within this framework, how should China’s current developmental stage be assessed?",
        "• How should China’s ‘socialist market economy’ be evaluated in relation to its institutional structure and outcomes? To what extent are market mechanisms compatible with socialist development, particularly when considered in light of both historical and contemporary experiences?",
        "• How should China’s position within the global capitalist system—and its points of tension and interaction with that system—be theoretically conceptualized?",
        "• To what extent do China’s economic and social transformations offer insights of broader relevance? What lessons, if any, can be drawn for other countries, including Türkiye, in terms of development strategies and institutional design?",
        "Two Chinese contributions that explicitly address these issues are presented in this issue by BRIQ: an academic piece by Prof. Dr. He Ganqiang and a chapter translated from a Chinese-language book by Prof. Dr. Xinhua Jian, two well-known Marxist political economists. Both academics have a wealth of experience in political economy and have made significant contributions to discussions of China’s socialist development.",
        "It is anticipated that these contributions will enrich ongoing theoretical and empirical discussions in the field. BRIQ therefore invites political economists in Türkiye and internationally to engage with these issues and to contribute original, high-quality research within this broad analytical framework.",
      ],
    },
  },
  "7-3": {
    tr: {
      title: "Kültürel Miras Yağması ve Emperyalist Hegemonya",
      paragraphs: [
        "İnsanlığın kuşaklar boyunca inşa ettiği medeniyetlerin somut taşıyıcısı olan kültürel mirasın ait olduğu coğrafyalardan koparılması, yalnızca bir suç değil, uluslararası sistemin adaletsizliğinin en sert tezahürlerinden biridir. Kültürel varlıkların çalınması ve başka merkezlere taşınması, özellikle sömürgecilik döneminde sistematik bir nitelik kazanmış; “keşif”, “koruma” ve “bilim” söylemleri altında yürütülen bu süreç, gerçekte emperyalist tahakkümün kültürel boyutunu oluşturmuştur. Bu yağma, yalnızca fiziksel bir transfer değil, aynı zamanda tarihin yeniden yazılmasıdır. Ezilen dünyanın kendi geçmişinden koparılmasıyla, Batı merkezli tarih anlatısı ve “medeniyet üstünlüğü” safsatası inşa edilmiştir.",
        "Bugün Batı başkentlerindeki müzeler, Asya, Afrika, Güney Amerika ve dünyanın diğer bölgelerinden taşınmış yüz binlerce eseri barındırmaktadır. Bununla birlikte, gelişen dünyadan çalınan kültürel varlıkların önemli bir bölümü müzayede evlerinde yüksek fiyatlarla el değiştirmekte ya da özel koleksiyonlarda tutulmaktadır. Küresel sanat piyasasının büyümesiyle birlikte bu akış daha da karmaşık hale gelmiş; yerel kazılardan uluslararası galerilere uzanan çok katmanlı bir kaçakçılık zinciri ortaya çıkmıştır. Bu zincirde eserler, sahte köken belgeleriyle “temizlenerek” yasal dolaşıma sokulmaktadır.",
        "Soğuk Savaş sonrası dönemde ve özellikle son yirmi yılda, kültürel miras yağması yeni bir ivme kazanmıştır. ABD’nin Afganistan ve Irak işgalleri ile 2011 sonrasında Suriye’ye yönelik parçalama operasyonları, emperyalist müdahalelerin kültürel varlıklar üzerinde ne denli yıkıcı sonuçlar doğurduğunu açıkça göstermiştir. Siyasi istikrarsızlık ve çatışma ortamlarında artan yasadışı kazılar, bu eserleri yalnızca küresel piyasaya taşımakla kalmamakta, aynı zamanda terör örgütleri ve organize suç ağları için önemli bir finansman kaynağı oluşturmaktadır. Mevcut veriler, bu alanın yıllık hacminin yüz milyonlarca dolardan birkaç milyar dolara kadar uzanan geniş bir aralıkta seyrettiğini göstermektedir.",
        "Bu tablo karşısında, kültürel varlıkların korunması ve iadesi meselesi, gelişen dünya ülkeleri için yalnızca bir kültür politikası değil, aynı zamanda egemenlik ve tarihsel adalet meselesidir. İade süreçleri, geçmişin telafisine yönelik sembolik adımlar olmanın ötesinde, uluslararası sistemde güvenin yeniden inşası açısından da kritik önemdedir. Ancak mevcut hukuki mekanizmalar ve uluslararası sözleşmeler sınırlı kalmaktadır.",
        "Sonuç olarak, kültürel mirasın yağmalanması insanlığın ortak hafızasına yönelmiş bir tehdittir. Bu nedenle mesele, tek tek ülkelerin değil, bütün ülkelerin ortak sorumluluğu olarak ele alınmalıdır. Bununla birlikte, yağmanın esas olarak gelişen dünyayı hedef aldığı ve eserlerin büyük ölçüde emperyalist merkezlerde toplandığı göz önüne alındığında, gelişen dünya ülkeleri arasındaki işbirliği bu alandaki mücadelenin güçlendirilmesi açısından belirleyici olacaktır. Kültürel varlıkların korunması ve iadesi için yürütülecek mücadele, kültürel geçmişine sahip çıkmanın yanı sıra daha adil, dengeli ve çok taraflı bir uluslararası düzenin inşasına katkı sunmak anlamına gelmektedir.",
      ],
    },
    en: {
      title: "The Plunder of Cultural Heritage and Imperialist Hegemony",
      paragraphs: [
        "The removal of cultural heritage, the tangible carrier of civilizations built by humanity over generations, from its places of origin is not merely a crime, but one of the most striking manifestations of injustice in the international system. The theft and transfer of cultural assets to distant centers acquired a systematic character, particularly during the colonial period. Conducted under the rhetoric of ‘discovery,’ ‘protection,’ and ‘science,’ this process in reality constituted the cultural dimension of imperial domination. Such plunder represents not only a physical displacement but also a rewriting of history itself. By severing the oppressed world from its own past, a Western-centric historical narrative has been constructed, along with the fallacy of ‘civilizational superiority.’",
        "Today, museums in Western capitals house hundreds of thousands of artifacts removed from Asia, Africa, South America, and other parts of the world. At the same time, a significant portion of cultural objects looted from the developing world circulates through auction houses at exorbitant prices or remains in private collections. With the expansion of the global art market, these flows have become increasingly complex, giving rise to multi-layered trafficking networks extending from local excavations to international galleries. Within this chain, artifacts are laundered into the legal market through fabricated provenance records.",
        "In the post–Cold War period, and especially over the past two decades, the looting of cultural heritage has gained renewed momentum. The U.S. invasions of Afghanistan and Iraq, along with the post-2011 operations aimed at fragmenting Syria, have clearly demonstrated the devastating impact of imperial interventions on cultural assets. In conditions of political instability and armed conflict, the increase in illicit excavations not only feeds global markets but also provides a significant source of financing for terrorist organizations and organized crime networks. Available estimates suggest that the annual scale of this illicit trade ranges from hundreds of millions to several billion dollars.",
        "In this context, the protection and restitution of cultural property are not merely matters of cultural policy for developing countries, but also of sovereignty and historical justice. Restitution processes go beyond symbolic acts of redress and are critical for rebuilding trust within the international system. However, existing legal frameworks and international conventions remain insufficient.",
        "Ultimately, the looting of cultural heritage constitutes a threat to the shared memory of humanity. It must therefore be addressed not as the responsibility of individual states alone, but as a collective responsibility of all countries. At the same time, given that this plunder disproportionately targets the developing world while the artifacts are largely concentrated in imperial centers, cooperation among developing countries will be decisive in strengthening this struggle. Efforts to protect and reclaim cultural property are not only about preserving the past, but also about contributing to the construction of a more just, balanced, and multilateral international order.",
      ],
    },
  },
};
