from pathlib import Path

article_platform = Path("app/components/ArticlePlatform.tsx")
text = article_platform.read_text(encoding="utf-8")

old_import = 'import { articleCitation } from "../article-citation";'
new_import = 'import { articleCitation, citationWithDoi } from "../article-citation";'
if old_import not in text:
    raise SystemExit("ArticlePlatform citation import not found")
text = text.replace(old_import, new_import, 1)

old_citation = '  const citation = details?.citation || articleCitation(article, locale);'
new_citation = '  const citation = citationWithDoi(details?.citation || articleCitation(article, locale), article.doi);'
if old_citation not in text:
    raise SystemExit("ArticlePlatform citation assignment not found")
text = text.replace(old_citation, new_citation, 1)

old_sidebar = '''          <div className="article-record-compact">\n            <div><span>{locale === "tr" ? "Cilt / Sayı" : "Volume / Issue"}</span><b>{article.volume} / {article.issue}</b></div>\n            <div><span>{locale === "tr" ? "Sayfa" : "Pages"}</span><b>{article.pages || "—"}</b></div>\n            <div><span>{locale === "tr" ? "Yayın" : "Published"}</span><b>{locale === "tr" ? article.season_tr : article.season_en} {article.year}</b></div>\n          </div>\n          <PublicationRecord locale={locale} history={history} doi={article.doi} />'''
new_sidebar = '''          <div className="article-record-compact">\n            <div><span>{locale === "tr" ? "Cilt / Sayı" : "Volume / Issue"}</span><b>{article.volume} / {article.issue}</b></div>\n            <div><span>{locale === "tr" ? "Sayfa" : "Pages"}</span><b>{article.pages || "—"}</b></div>\n            <div><span>{locale === "tr" ? "Yayın" : "Published"}</span><b>{locale === "tr" ? article.season_tr : article.season_en} {article.year}</b></div>\n            {article.doi && <div className="publication-doi"><span>DOI</span><b><a href={`https://doi.org/${article.doi}`} target="_blank" rel="noreferrer">{article.doi}</a></b></div>}\n          </div>\n          <PublicationRecord locale={locale} history={history} />'''
if old_sidebar not in text:
    raise SystemExit("ArticlePlatform sidebar block not found")
text = text.replace(old_sidebar, new_sidebar, 1)
article_platform.write_text(text, encoding="utf-8")

Path("app/article-citation.ts").write_text('''import type { ArchiveArticle } from "./archive";\n\nfunction normalizedDoi(doi: string) {\n  return doi.replace(/^https?:\\/\\/doi\\.org\\//i, "").trim();\n}\n\nfunction escapeRegExp(value: string) {\n  return value.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\\\$&");\n}\n\nexport function citationWithDoi(citation: string, doi?: string | null) {\n  const base = citation.trim();\n  if (!doi) return base;\n\n  const cleanDoi = normalizedDoi(doi);\n  if (!cleanDoi) return base;\n  const url = `https://doi.org/${cleanDoi}`;\n  const doiPattern = new RegExp(`(?:https?:\\\\/\\\\/doi\\\\.org\\\\/|doi\\\\s*:?\\\\s*)${escapeRegExp(cleanDoi)}`, "i");\n\n  if (doiPattern.test(base)) {\n    return base.replace(doiPattern, url).replace(new RegExp(`${escapeRegExp(url)}[.;,]$`), url);\n  }\n  return `${base} ${url}`;\n}\n\nexport function articleCitation(article: ArchiveArticle, locale: "tr" | "en") {\n  const stored = locale === "tr" ? article.citation_tr : article.citation_en;\n  if (stored) return citationWithDoi(stored, article.doi);\n  const title = locale === "tr" ? article.title_tr : (article.title_en || article.title_tr);\n  const journal = locale === "tr" ? "BRIQ Kuşak ve Yol Girişimi Dergisi" : "BRIQ Belt & Road Initiative Quarterly";\n  const pages = article.pages ? `, ${article.pages}` : "";\n  return citationWithDoi(`${article.author} (${article.year}). ${title}. ${journal}, ${article.volume}(${article.issue})${pages}.`, article.doi);\n}\n''', encoding="utf-8")

Path("app/components/PublicationRecord.tsx").write_text('''import type { Locale } from "../authors";\n\nexport type PublicationHistory = {\n  received?: string | null;\n  revised?: string | null;\n  accepted?: string | null;\n  publishedOnline?: string | null;\n};\n\nfunction formatDate(value: string | null | undefined, locale: Locale) {\n  if (!value) return "—";\n  if (!/^\\d{4}-\\d{2}-\\d{2}$/.test(value)) return value;\n  return new Intl.DateTimeFormat(locale === "tr" ? "tr-TR" : "en-GB", {\n    day: "numeric",\n    month: "long",\n    year: "numeric",\n    timeZone: "UTC",\n  }).format(new Date(`${value}T00:00:00Z`));\n}\n\nexport function PublicationRecord({\n  locale,\n  history,\n}: {\n  locale: Locale;\n  history?: PublicationHistory;\n}) {\n  const labels: [string, string | null | undefined][] = locale === "tr"\n    ? [\n        ["Geliş", history?.received],\n        ["Revizyon", history?.revised],\n        ["Kabul", history?.accepted],\n        ["Çevrimiçi yayım", history?.publishedOnline],\n      ]\n    : [\n        ["Received", history?.received],\n        ["Revised", history?.revised],\n        ["Accepted", history?.accepted],\n        ["Published online", history?.publishedOnline],\n      ];\n\n  return (\n    <div className="publication-record-group">\n      <p className="article-sidebar-heading">\n        {locale === "tr" ? "Makale geçmişi" : "Article history"}\n      </p>\n      <dl className="publication-history">\n        {labels.map(([label, value]) => (\n          <div className={value ? "" : "is-empty"} key={label}>\n            <dt>{label}</dt>\n            <dd>{formatDate(value, locale)}</dd>\n          </div>\n        ))}\n      </dl>\n    </div>\n  );\n}\n''', encoding="utf-8")

Path("app/components/CitationTools.tsx").write_text('''"use client";\n\nimport { useState } from "react";\n\nfunction CitationText({ value }: { value: string }) {\n  const match = value.match(/^(.*?)(https:\\/\\/doi\\.org\\/10\\.\\S+)$/i);\n  if (!match) return <>{value}</>;\n  return <>\n    {match[1]}\n    <a className="reference-inline-link" href={match[2]} target="_blank" rel="noreferrer">{match[2]}</a>\n  </>;\n}\n\nexport function CitationTools({ citation, slug, locale }: { citation: string; slug: string; locale: "tr" | "en" }) {\n  const [copied, setCopied] = useState(false);\n  const formattedCitation = citation.replace(/^\\s*(?:Atıf|Citation)\\s*/i, "").trim();\n  const copy = async () => {\n    await navigator.clipboard.writeText(formattedCitation);\n    setCopied(true);\n    window.setTimeout(() => setCopied(false), 1800);\n  };\n  return (\n    <div className="citation-toolbox">\n      <div className="citation-toolbox-heading">\n        <span>{locale === "tr" ? "Önerilen gösterim" : "Formatted citation"}</span>\n        <b>APA 7</b>\n      </div>\n      <blockquote><p><CitationText value={formattedCitation} /></p></blockquote>\n      <div className="citation-toolbox-actions">\n        <button type="button" onClick={copy}>\n          <svg aria-hidden="true" viewBox="0 0 24 24"><rect x="8" y="8" width="11" height="11" rx="1.5"/><path d="M16 8V5.5A1.5 1.5 0 0 0 14.5 4h-10A1.5 1.5 0 0 0 3 5.5v10A1.5 1.5 0 0 0 4.5 17H8"/></svg>\n          <span>{copied ? (locale === "tr" ? "Kopyalandı" : "Copied") : (locale === "tr" ? "Atıfı kopyala" : "Copy citation")}</span>\n        </button>\n        <div className="citation-export-group">\n          <span>{locale === "tr" ? "Dışa aktar" : "Export"}</span>\n          <a href={`/citations/${slug}.ris?locale=${locale}`}><span>RIS</span><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M12 4v11m0 0 4-4m-4 4-4-4M5 20h14"/></svg></a>\n          <a href={`/citations/${slug}.bib?locale=${locale}`}><span>BibTeX</span><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M12 4v11m0 0 4-4m-4 4-4-4M5 20h14"/></svg></a>\n          <a href={`/citations/${slug}.enw?locale=${locale}`}><span>EndNote</span><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M12 4v11m0 0 4-4m-4 4-4-4M5 20h14"/></svg></a>\n        </div>\n      </div>\n    </div>\n  );\n}\n''', encoding="utf-8")

print("DOI presentation and citation patch applied.")
